name: Build Wrapped Anchor Image
description: Builds anchor image with pnpm and w/out yarn
inputs:
  runner-os:
    description: the operating system
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Get ProjectSerum Version
      uses: ./.github/actions/projectserum_version
      id: get-version

    - name: cache docker build image
      id: cache-image
      uses: actions/cache@v4
      with:
        path: contracts/docker-build.tar
        key: ${{ inputs.runner-os }}-docker-pnpm-build-${{ steps.get-version.outputs.projectserum_version }}-${{ hashFiles('contracts/**/Cargo.lock') }}

    - name: build & save image
      if: steps.cache-image.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd contracts
        docker buildx build . -t chainlink-solana:build --build-arg ANCHOR_CLI=${{ steps.get-version.outputs.projectserum_version }}
        docker save chainlink-solana > docker-build.tar
        cd ../
