package chainwriter

import (
	"context"
	"encoding/json"
	"fmt"
	"math/big"
	"reflect"

	"github.com/gagliardetto/solana-go"
	"github.com/gagliardetto/solana-go/rpc"

	commoncodec "github.com/smartcontractkit/chainlink-common/pkg/codec"
	"github.com/smartcontractkit/chainlink-common/pkg/codec/encodings/binary"
	"github.com/smartcontractkit/chainlink-common/pkg/services"
	"github.com/smartcontractkit/chainlink-common/pkg/types"

	"github.com/smartcontractkit/chainlink-solana/pkg/solana/client"
	"github.com/smartcontractkit/chainlink-solana/pkg/solana/codec"
	"github.com/smartcontractkit/chainlink-solana/pkg/solana/fees"
	"github.com/smartcontractkit/chainlink-solana/pkg/solana/txm"
)

type SolanaChainWriterService struct {
	reader client.Reader
	txm    txm.Txm
	ge     fees.Estimator
	codec  types.Codec
	config ChainWriterConfig
}

type ChainWriterConfig struct {
	Programs map[string]ProgramConfig
}

type ProgramConfig struct {
	Methods map[string]MethodConfig
	IDL     string
}

type MethodConfig struct {
	FromAddress        string
	InputModifications commoncodec.ModifiersConfig
	DecodeLocation     string
	DataType           reflect.Type
	DecodedTypeName    string
	ChainSpecificName  string
	LookupTables       LookupTables
	Accounts           []Lookup
	// Location in the decoded data where the debug ID is stored
	DebugIDLocation string
}

type Lookup interface {
}

// AccountConstant represents a fixed address, provided in Base58 format, converted into a `solana.PublicKey`.
type AccountConstant struct {
	Name       string
	Address    string
	IsSigner   bool
	IsWritable bool
}

// AccountLookup dynamically derives an account address from decoded data using a specified location path.
type AccountLookup struct {
	Name       string
	Location   string
	IsSigner   bool
	IsWritable bool
}

// PDALookups generates Program Derived Addresses (PDA) by combining a derived public key with one or more seeds.
type PDALookups struct {
	Name string
	// The public key of the PDA to be combined with seeds. If there are multiple PublicKeys
	// there will be multiple PDAs generated by combining each PublicKey with the seeds.
	PublicKey Lookup
	// Seeds to be derived from an additional lookup
	Seeds      []Lookup
	IsSigner   bool
	IsWritable bool
}

type ValueLookup struct {
	Location string
}

// LookupTables represents a list of lookup tables that are used to derive addresses for a program.
type LookupTables struct {
	DerivedLookupTables []DerivedLookupTable
	StaticLookupTables  []string
}

// DerivedLookupTable represents a lookup table that is used to derive addresses for a program.
type DerivedLookupTable struct {
	Name           string
	Accounts       Lookup
	EncodedTypeIDL string
	DecodedType    reflect.Type
}

// AccountsFromLookupTable extracts accounts from a lookup table that was previously read and stored in memory.
type AccountsFromLookupTable struct {
	LookupTablesName string
	IncludeIndexes   []int
}

func NewSolanaChainWriterService(reader client.Reader, txm txm.Txm, ge fees.Estimator, config ChainWriterConfig) *SolanaChainWriterService {
	return &SolanaChainWriterService{
		reader: reader,
		txm:    txm,
		ge:     ge,
		config: config,
	}
}

/*
GetAddresses resolves account addresses from various `Lookup` configurations to build the required `solana.AccountMeta` list
for Solana transactions. It handles constant addresses, dynamic lookups, program-derived addresses (PDAs), and lookup tables.

### Parameters:
- `ctx`: Context for request lifecycle management.
- `decoded`: Decoded data used for dynamic lookups.
- `accounts`: List of `Lookup` configurations specifying how addresses are derived.
- `derivedTableMap`: Map of pre-loaded lookup table addresses.
- `debugID`: Debug identifier for tracing errors.

### Return:
- A slice of `solana.AccountMeta` containing derived addresses and associated metadata.

### Account Types:
1. **AccountConstant**:
  - A fixed address, provided in Base58 format, converted into a `solana.PublicKey`.
  - Example: A pre-defined fee payer or system account.

2. **AccountLookup**:
  - Dynamically derived from decoded data using a specified location path (e.g., `user.walletAddress`).
  - If the lookup table is pre-loaded, the address is fetched from `derivedTableMap`.

3. **PDALookups**:
  - Generates Program Derived Addresses (PDA) by combining a derived public key with one or more seeds.
  - Seeds can be `AddressSeeds` (public keys from the decoded data) or `ValueSeeds` (byte arrays).
  - Ensures there is only one public key if multiple seeds are provided.

### Error Handling:
- Errors are wrapped with the `debugID` for easier tracing.
*/
// GetAddresses resolves account addresses from various `Lookup` configurations to build the required `solana.AccountMeta` list
// for Solana transactions.
func (s *SolanaChainWriterService) GetAddresses(ctx context.Context, decoded any, accounts []Lookup, derivedTableMap map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error) {
	var addresses []*solana.AccountMeta
	for _, accountConfig := range accounts {
		meta, err := s.getAccountMeta(ctx, decoded, accountConfig, derivedTableMap, debugID)
		if err != nil {
			return nil, err
		}
		addresses = append(addresses, meta...)
	}
	return addresses, nil
}

// getAccountMeta processes a single account configuration and returns the corresponding `solana.AccountMeta` slice.
func (s *SolanaChainWriterService) getAccountMeta(ctx context.Context, decoded any, accountConfig Lookup, derivedTableMap map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error) {
	switch lookup := accountConfig.(type) {
	case AccountConstant:
		return s.handleAccountConstant(lookup, debugID)
	case AccountLookup:
		return s.handleAccountLookup(decoded, lookup, derivedTableMap, debugID)
	case PDALookups:
		return s.handlePDALookup(ctx, decoded, lookup, derivedTableMap, debugID)
	default:
		return nil, errorWithDebugID(fmt.Errorf("unsupported account type: %T", lookup), debugID)
	}
}

// handleAccountConstant processes an `AccountConstant` and returns the corresponding `solana.AccountMeta`.
func (s *SolanaChainWriterService) handleAccountConstant(lookup AccountConstant, debugID string) ([]*solana.AccountMeta, error) {
	address, err := solana.PublicKeyFromBase58(lookup.Address)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error getting account from constant: %w", err), debugID)
	}
	return []*solana.AccountMeta{
		{
			PublicKey:  address,
			IsSigner:   lookup.IsSigner,
			IsWritable: lookup.IsWritable,
		},
	}, nil
}

// handleAccountLookup processes an `AccountLookup` by either fetching from the lookup table or dynamically deriving the address.
func (s *SolanaChainWriterService) handleAccountLookup(decoded any, lookup AccountLookup, derivedTableMap map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error) {
	if derivedAddresses, ok := derivedTableMap[lookup.Name]; ok {
		return derivedAddresses, nil
	}

	derivedAddresses, err := GetAddressAtLocation(decoded, lookup.Location, debugID)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error getting account from lookup: %w", err), debugID)
	}

	var metas []*solana.AccountMeta
	for _, address := range derivedAddresses {
		metas = append(metas, &solana.AccountMeta{
			PublicKey:  address,
			IsSigner:   lookup.IsSigner,
			IsWritable: lookup.IsWritable,
		})
	}
	return metas, nil
}

// handlePDALookup processes a `PDALookups` by resolving seeds and generating the PDA address.
func (s *SolanaChainWriterService) handlePDALookup(ctx context.Context, decoded any, lookup PDALookups, derivedTableMap map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error) {
	publicKeys, err := s.GetAddresses(ctx, decoded, []Lookup{lookup.PublicKey}, derivedTableMap, debugID)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error getting public key for PDALookups: %w", err), debugID)
	}

	seeds, err := s.getSeedBytes(ctx, lookup, decoded, derivedTableMap, debugID)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error getting seeds for PDALookups: %w", err), debugID)
	}

	return s.generatePDAs(publicKeys, seeds, lookup, debugID)
}

// getSeedBytes extracts the seeds for the PDALookups.
// It handles both AddressSeeds (which are public keys) and ValueSeeds (which are byte arrays from decoded data).
func (s *SolanaChainWriterService) getSeedBytes(ctx context.Context, lookup PDALookups, decoded any, derivedTableMap map[string][]*solana.AccountMeta, debugID string) ([][]byte, error) {
	var seedBytes [][]byte

	// Process AddressSeeds first (e.g., public keys)
	for _, seed := range lookup.AddressSeeds {
		// Get the address(es) at the seed location
		seedAddresses, err := s.GetAddresses(ctx, decoded, []Lookup{seed}, derivedTableMap, debugID)
		if err != nil {
			return nil, errorWithDebugID(fmt.Errorf("error getting address seed: %w", err), debugID)
		}

		// Add each address seed as bytes
		for _, address := range seedAddresses {
			seedBytes = append(seedBytes, address.PublicKey.Bytes())
		}
	}

	// Process ValueSeeds (e.g., raw byte values found in decoded data)
	for _, valueSeed := range lookup.ValueSeeds {
		// Get the byte array value at the seed location
		values, err := GetValueAtLocation(decoded, valueSeed.Location)
		if err != nil {
			return nil, errorWithDebugID(fmt.Errorf("error getting value seed: %w", err), debugID)
		}

		// Add each value seed (which is a byte array)
		seedBytes = append(seedBytes, values...)
	}

	return seedBytes, nil
}

// generatePDAs generates program-derived addresses (PDAs) from public keys and seeds.
func (s *SolanaChainWriterService) generatePDAs(publicKeys []*solana.AccountMeta, seeds [][]byte, lookup PDALookups, debugID string) ([]*solana.AccountMeta, error) {
	if len(seeds) > 1 && len(publicKeys) > 1 {
		return nil, errorWithDebugID(fmt.Errorf("multiple public keys and multiple seeds are not allowed"), debugID)
	}

	var addresses []*solana.AccountMeta
	for _, publicKeyMeta := range publicKeys {
		address, _, err := solana.FindProgramAddress(seeds, publicKeyMeta.PublicKey)
		if err != nil {
			return nil, errorWithDebugID(fmt.Errorf("error finding program address: %w", err), debugID)
		}
		addresses = append(addresses, &solana.AccountMeta{
			PublicKey:  address,
			IsSigner:   lookup.IsSigner,
			IsWritable: lookup.IsWritable,
		})
	}
	return addresses, nil
}

func (s *SolanaChainWriterService) getDerivedTableMap(ctx context.Context, lookupTables []DerivedLookupTable, debugID string) ([]*solana.AccountMeta, []string, map[string][]*solana.AccountMeta, error) {
	var accounts []*solana.AccountMeta
	var lookupTableAddresses []string
	var addressMap = make(map[string][]*solana.AccountMeta)

	for _, lookup := range lookupTables {
		lookupTableMap, tableAddresses, err := s.LoadTable(lookup, ctx, s.reader, addressMap, debugID)
		if err != nil {
			return nil, nil, nil, errorWithDebugID(fmt.Errorf("error loading lookup table: %w", err), debugID)
		}
		for _, address := range tableAddresses {
			lookupTableAddresses = append(lookupTableAddresses, address.PublicKey.String())
		}
		for name, addressList := range lookupTableMap {
			for _, address := range addressList {
				accounts = append(accounts, address)
			}
			addressMap[name] = addressList
		}
	}
	return accounts, lookupTableAddresses, addressMap, nil
}

// LoadTable fetches addresses specified by Identifier, loads data for each, and decodes it into solana.PublicKey slices.
func (s *SolanaChainWriterService) LoadTable(rlt DerivedLookupTable, ctx context.Context, reader client.Reader, derivedTableMap map[string][]*solana.AccountMeta, debugID string) (map[string][]*solana.AccountMeta, []*solana.AccountMeta, error) {
	// Use GetAddresses to resolve all addresses specified by Identifier.
	lookupTableAddresses, err := s.GetAddresses(ctx, nil, []Lookup{rlt.Identifier}, derivedTableMap, debugID)
	if err != nil {
		return nil, nil, errorWithDebugID(fmt.Errorf("error resolving addresses for lookup table: %w", err), debugID)
	}

	// Map to store address metadata grouped by location.
	resultMap := make(map[string][]*solana.AccountMeta)
	for _, addressMeta := range lookupTableAddresses {
		// Fetch account data for each resolved address.
		accountInfo, err := reader.GetAccountInfoWithOpts(ctx, addressMeta.PublicKey, &rpc.GetAccountInfoOpts{
			Encoding:   "base64",
			Commitment: rpc.CommitmentConfirmed,
		})
		if err != nil || accountInfo == nil || accountInfo.Value == nil {
			return nil, nil, errorWithDebugID(fmt.Errorf("error fetching account info for address %s: %w", addressMeta.PublicKey.String(), err), debugID)
		}

		// Decode account data based on the IDL specified in EncodedTypeIDL.
		decodedData, err := rlt.decodeAccountData(accountInfo.Value.Data.GetBinary(), debugID)
		if err != nil {
			return nil, nil, errorWithDebugID(fmt.Errorf("error decoding data for address %s: %w", addressMeta.PublicKey.String(), err), debugID)
		}

		// Get derived addresses from the decoded data for each location specified.
		for _, location := range rlt.Locations {
			derivedAddresses, err := s.GetAddresses(ctx, decodedData, []Lookup{location}, derivedTableMap, debugID)
			if err != nil {
				return nil, nil, errorWithDebugID(fmt.Errorf("error resolving derived addresses: %w", err), debugID)
			}
			resultMap[fmt.Sprintf("%s.%s", rlt.Name, location.Name)] = derivedAddresses
		}
	}
	return resultMap, lookupTableAddresses, nil
}

// Decode account data for the DerivedLookupTable based on its EncodedTypeIDL.
func (rlt *DerivedLookupTable) decodeAccountData(data []byte, debugID string) (any, error) {
	var idl codec.IDL
	err := json.Unmarshal([]byte(rlt.EncodedTypeIDL), &idl)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error unmarshalling IDL: %w", err), debugID)
	}

	cwCodec, err := codec.NewIDLAccountCodec(idl, binary.LittleEndian())
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error creating IDLAccountCodec: %w", err), debugID)
	}

	decoded := reflect.New(rlt.DecodedType).Interface()
	err = cwCodec.Decode(nil, data, decoded, "")
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error decoding account data: %w", err), debugID)
	}
	return decoded, nil
}

func (s *SolanaChainWriterService) GetLookupTables(ctx context.Context, lookupTables []string, debugID string) (map[solana.PublicKey]solana.PublicKeySlice, error) {
	tables := make(map[solana.PublicKey]solana.PublicKeySlice)

	for _, addressStr := range lookupTables {
		// Convert the string address to solana.PublicKey
		tableAddress, err := solana.PublicKeyFromBase58(addressStr)
		if err != nil {
			return nil, errorWithDebugID(fmt.Errorf("invalid lookup table address: %s, error: %w", addressStr, err), debugID)
		}

		// Fetch the lookup table data from the blockchain
		accountInfo, err := s.reader.GetAccountInfoWithOpts(ctx, tableAddress, &rpc.GetAccountInfoOpts{
			Encoding:   "base64",
			Commitment: rpc.CommitmentConfirmed,
		})
		if err != nil {
			return nil, errorWithDebugID(fmt.Errorf("error fetching account info for lookup table %s: %w", addressStr, err), debugID)
		}
		if accountInfo == nil || accountInfo.Value == nil {
			return nil, errorWithDebugID(fmt.Errorf("no data found for lookup table at address: %s", addressStr), debugID)
		}

		// Decode and extract public keys within the lookup table
		addresses, err := decodeLookupTable(accountInfo.Value.Data.GetBinary())
		if err != nil {
			return nil, errorWithDebugID(fmt.Errorf("error decoding lookup table data for %s: %w", addressStr, err), debugID)
		}

		// Add the addresses to the lookup table map
		tables[tableAddress] = addresses
	}
	return tables, nil
}

func decodeLookupTable(data []byte) (solana.PublicKeySlice, error) {
	// Example logic to decode lookup table data; you may need to adjust based on the actual format of the data.
	var addresses solana.PublicKeySlice

	// Assuming the data is a list of 32-byte public keys in binary format:
	for i := 0; i < len(data); i += solana.PublicKeyLength {
		if i+solana.PublicKeyLength > len(data) {
			return nil, fmt.Errorf("invalid lookup table data length")
		}
		address := solana.PublicKeyFromBytes(data[i : i+solana.PublicKeyLength])
		addresses = append(addresses, address)
	}

	return addresses, nil
}

func (s *SolanaChainWriterService) SubmitTransaction(ctx context.Context, contractName, method string, args any, transactionID string, toAddress string, meta *types.TxMeta, value *big.Int) error {
	programConfig := s.config.Programs[contractName]
	methodConfig := programConfig.Methods[method]

	data, ok := args.([]byte)
	if !ok {
		return fmt.Errorf("Unable to convert args to []byte")
	}

	// get inner encoded data from the encoded args
	encoded, err := GetValueAtLocation(data, methodConfig.DecodeLocation)
	if err != nil {
		return fmt.Errorf("error getting value at location: %w", err)
	}

	// Create an instance of the type defined by methodConfig.DataType
	decoded := reflect.New(methodConfig.DataType).Interface()
	err = s.codec.Decode(ctx, encoded[0], decoded, methodConfig.DecodedTypeName)

	// Configure debug ID
	debugID := ""
	if methodConfig.DebugIDLocation != "" {
		debugID, err = GetDebugIDAtLocation(decoded, methodConfig.DebugIDLocation)
		if err != nil {
			return errorWithDebugID(fmt.Errorf("error getting debug ID from decoded data: %w", err), debugID)
		}
	}

	// Read lookup tables from on-chain
	lookupTableAddresses, derivedTableMap, err := s.getDerivedTableMap(ctx, methodConfig.DerivedLookupTables, debugID)
	if err != nil {
		return errorWithDebugID(fmt.Errorf("error getting readable table map: %w", err), debugID)
	}

	// Lookup configured account addresses from decoded data
	accounts, err := s.GetAddresses(ctx, decoded, methodConfig.Accounts, derivedTableMap, debugID)
	if err != nil {
		return errorWithDebugID(fmt.Errorf("error getting addresses from decoded data: %w", err), debugID)
	}

	// get current latest blockhash, this can be overwritten by the TXM
	blockhash, err := s.reader.LatestBlockhash(ctx)

	programId, err := solana.PublicKeyFromBase58(contractName)
	if err != nil {
		return errorWithDebugID(fmt.Errorf("Error getting programId: %w", err), debugID)
	}

	// Encode payload for chain, apply modifiers and borsh-encode
	encodedPayload, err := s.codec.Encode(ctx, args, codec.WrapItemType(contract, method, true))
	if err != nil {
		return errorWithDebugID(fmt.Errorf("error encoding data: %w", err), debugID)
	}

	feePayer, err := solana.PublicKeyFromBase58(methodConfig.FromAddress)
	if err != nil {
		return errorWithDebugID(fmt.Errorf("error getting fee payer: %w", err), debugID)
	}

	tx, err := solana.NewTransaction(
		[]solana.Instruction{
			solana.NewInstruction(programId, accounts, encodedPayload),
		},
		blockhash.Value.Blockhash,
		solana.TransactionPayer(feePayer),
		solana.TransactionAddressTables(lookupTableAddresses),
	)

	if err != nil {
		return errorWithDebugID(fmt.Errorf("error creating new transaction: %w", err), debugID)
	}

	if err = s.txm.Enqueue(ctx, accounts[0].PublicKey.String(), tx, transactionID); err != nil {
		return errorWithDebugID(fmt.Errorf("error on sending trasnaction to TXM: %w", err), debugID)
	}
	return nil
}

var (
	_ services.Service  = &SolanaChainWriterService{}
	_ types.ChainWriter = &SolanaChainWriterService{}
)

// GetTransactionStatus returns the current status of a transaction in the underlying chain's TXM.
func (s *SolanaChainWriterService) GetTransactionStatus(ctx context.Context, transactionID string) (types.TransactionStatus, error) {
	return types.Unknown, nil
}

// GetFeeComponents retrieves the associated gas costs for executing a transaction.
func (s *SolanaChainWriterService) GetFeeComponents(ctx context.Context) (*types.ChainFeeComponents, error) {
	if s.ge == nil {
		return nil, fmt.Errorf("gas estimator not available")
	}

	fee := s.ge.BaseComputeUnitPrice()
	return &types.ChainFeeComponents{
		ExecutionFee:        big.NewInt(int64(fee)),
		DataAvailabilityFee: nil,
	}, nil
}

func (s *SolanaChainWriterService) Start(context.Context) error {
	return nil
}

func (s *SolanaChainWriterService) Close() error {
	return nil
}

func (s *SolanaChainWriterService) HealthReport() map[string]error {
	return nil
}

func (s *SolanaChainWriterService) Name() string {
	return ""
}

func (s *SolanaChainWriterService) Ready() error {
	return nil
}
