package chainwriter

import (
	"context"
	"fmt"
	"reflect"

	ag_binary "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
	addresslookuptable "github.com/gagliardetto/solana-go/programs/address-lookup-table"
	"github.com/gagliardetto/solana-go/rpc"

	"github.com/smartcontractkit/chainlink-solana/pkg/solana/client"
)

type Lookup interface {
	Resolve(ctx context.Context, args any, derivedTableMap map[string]map[string][]*solana.AccountMeta, reader client.Reader) ([]*solana.AccountMeta, error)
}

// AccountConstant represents a fixed address, provided in Base58 format, converted into a `solana.PublicKey`.
type AccountConstant struct {
	Name       string
	Address    string
	IsSigner   bool
	IsWritable bool
}

// AccountLookup dynamically derives an account address from args using a specified location path.
type AccountLookup struct {
	Name       string
	Location   string
	IsSigner   bool
	IsWritable bool
}

// PDALookups generates Program Derived Addresses (PDA) by combining a derived public key with one or more seeds.
type PDALookups struct {
	Name string
	// The public key of the PDA to be combined with seeds. If there are multiple PublicKeys
	// there will be multiple PDAs generated by combining each PublicKey with the seeds.
	PublicKey Lookup
	// Seeds to be derived from an additional lookup
	Seeds      []Lookup
	IsSigner   bool
	IsWritable bool
	// OPTIONAL: On-chain location and type of desired data from PDA (e.g. a sub-account of the data account)
	InternalField InternalField
}

type InternalField struct {
	Type     reflect.Type
	Location string
}

// LookupTables represents a list of lookup tables that are used to derive addresses for a program.
type LookupTables struct {
	DerivedLookupTables []DerivedLookupTable
	StaticLookupTables  []solana.PublicKey
}

// DerivedLookupTable represents a lookup table that is used to derive addresses for a program.
type DerivedLookupTable struct {
	Name     string
	Accounts Lookup
}

// AccountsFromLookupTable extracts accounts from a lookup table that was previously read and stored in memory.
type AccountsFromLookupTable struct {
	LookupTableName string
	IncludeIndexes  []int
}

func (ac AccountConstant) Resolve(_ context.Context, _ any, _ map[string]map[string][]*solana.AccountMeta, _ client.Reader) ([]*solana.AccountMeta, error) {
	address, err := solana.PublicKeyFromBase58(ac.Address)
	if err != nil {
		return nil, fmt.Errorf("error getting account from constant: %w", err)
	}
	return []*solana.AccountMeta{
		{
			PublicKey:  address,
			IsSigner:   ac.IsSigner,
			IsWritable: ac.IsWritable,
		},
	}, nil
}

func (al AccountLookup) Resolve(_ context.Context, args any, _ map[string]map[string][]*solana.AccountMeta, _ client.Reader) ([]*solana.AccountMeta, error) {
	derivedValues, err := GetValuesAtLocation(args, al.Location)
	if err != nil {
		return nil, fmt.Errorf("error getting account from lookup: %w", err)
	}

	var metas []*solana.AccountMeta
	for _, address := range derivedValues {
		metas = append(metas, &solana.AccountMeta{
			PublicKey:  solana.PublicKeyFromBytes(address),
			IsSigner:   al.IsSigner,
			IsWritable: al.IsWritable,
		})
	}
	return metas, nil
}

func (alt AccountsFromLookupTable) Resolve(_ context.Context, _ any, derivedTableMap map[string]map[string][]*solana.AccountMeta, _ client.Reader) ([]*solana.AccountMeta, error) {
	// Fetch the inner map for the specified lookup table name
	innerMap, ok := derivedTableMap[alt.LookupTableName]
	if !ok {
		return nil, fmt.Errorf("lookup table not found: %s", alt.LookupTableName)
	}

	var result []*solana.AccountMeta

	// If no indices are specified, include all addresses
	if len(alt.IncludeIndexes) == 0 {
		for _, metas := range innerMap {
			result = append(result, metas...)
		}
		return result, nil
	}

	// Otherwise, include only addresses at the specified indices
	for publicKey, metas := range innerMap {
		for _, index := range alt.IncludeIndexes {
			if index < 0 || index >= len(metas) {
				return nil, fmt.Errorf("invalid index %d for account %s in lookup table %s", index, publicKey, alt.LookupTableName)
			}
			result = append(result, metas[index])
		}
	}

	return result, nil
}

func (pda PDALookups) Resolve(ctx context.Context, args any, derivedTableMap map[string]map[string][]*solana.AccountMeta, reader client.Reader) ([]*solana.AccountMeta, error) {
	publicKeys, err := GetAddresses(ctx, args, []Lookup{pda.PublicKey}, derivedTableMap, reader)
	if err != nil {
		return nil, fmt.Errorf("error getting public key for PDALookups: %w", err)
	}

	seeds, err := getSeedBytes(ctx, pda, args, derivedTableMap, reader)
	if err != nil {
		return nil, fmt.Errorf("error getting seeds for PDALookups: %w", err)
	}

	pdas, err := generatePDAs(publicKeys, seeds, pda)
	if err != nil {
		return nil, fmt.Errorf("error generating PDAs: %w", err)
	}

	if pda.InternalField.Location == "" {
		return pdas, nil
	}

	// If a decoded location is specified, fetch the data at that location
	var result []*solana.AccountMeta
	for _, accountMeta := range pdas {
		accountInfo, err := reader.GetAccountInfoWithOpts(ctx, accountMeta.PublicKey, &rpc.GetAccountInfoOpts{
			Encoding:   "base64",
			Commitment: rpc.CommitmentFinalized,
		})

		if err != nil || accountInfo == nil || accountInfo.Value == nil {
			return nil, fmt.Errorf("error fetching account info for PDA account: %s, error: %w", accountMeta.PublicKey.String(), err)
		}

		decoded, err := decodeBorshIntoType(accountInfo.GetBinary(), pda.InternalField.Type)
		if err != nil {
			return nil, fmt.Errorf("error decoding Borsh data dynamically: %w", err)
		}

		value, err := GetValuesAtLocation(decoded, pda.InternalField.Location)
		if err != nil {
			return nil, fmt.Errorf("error getting value at location: %w", err)
		}
		if len(value) > 1 {
			return nil, fmt.Errorf("multiple values found at location: %s", pda.InternalField.Location)
		}

		result = append(result, &solana.AccountMeta{
			PublicKey:  solana.PublicKeyFromBytes(value[0]),
			IsSigner:   accountMeta.IsSigner,
			IsWritable: accountMeta.IsWritable,
		})
	}
	return result, nil
}

func decodeBorshIntoType(data []byte, typ reflect.Type) (interface{}, error) {
	// Ensure the type is a struct
	if typ.Kind() != reflect.Struct {
		return nil, fmt.Errorf("provided type is not a struct: %s", typ.Kind())
	}

	// Create a new instance of the type
	instance := reflect.New(typ).Interface()

	// Decode using Borsh
	err := ag_binary.NewBorshDecoder(data).Decode(instance)
	if err != nil {
		return nil, fmt.Errorf("error decoding Borsh data: %w", err)
	}

	// Return the underlying value (not a pointer)
	return reflect.ValueOf(instance).Elem().Interface(), nil
}

// getSeedBytes extracts the seeds for the PDALookups.
// It handles both AddressSeeds (which are public keys) and ValueSeeds (which are byte arrays from input args).
func getSeedBytes(ctx context.Context, lookup PDALookups, args any, derivedTableMap map[string]map[string][]*solana.AccountMeta, reader client.Reader) ([][]byte, error) {
	var seedBytes [][]byte

	for _, seed := range lookup.Seeds {
		if lookupSeed, ok := seed.(AccountLookup); ok {
			// Get value from a location (This doesn't have to be an address, it can be any value)
			bytes, err := GetValuesAtLocation(args, lookupSeed.Location)
			if err != nil {
				return nil, fmt.Errorf("error getting address seed: %w", err)
			}
			// validate seed length
			for _, b := range bytes {
				if len(b) > solana.MaxSeedLength {
					return nil, fmt.Errorf("seed byte array exceeds maximum length of %d: got %d bytes", solana.MaxSeedLength, len(b))
				}
				seedBytes = append(seedBytes, b)
			}
		} else {
			// Get address seeds from the lookup
			seedAddresses, err := GetAddresses(ctx, args, []Lookup{seed}, derivedTableMap, reader)
			if err != nil {
				return nil, fmt.Errorf("error getting address seed: %w", err)
			}

			// Add each address seed as bytes
			for _, address := range seedAddresses {
				seedBytes = append(seedBytes, address.PublicKey.Bytes())
			}
		}
	}

	return seedBytes, nil
}

// generatePDAs generates program-derived addresses (PDAs) from public keys and seeds.
func generatePDAs(publicKeys []*solana.AccountMeta, seeds [][]byte, lookup PDALookups) ([]*solana.AccountMeta, error) {
	if len(seeds) > solana.MaxSeeds {
		return nil, fmt.Errorf("seed maximum exceeded: %d", len(seeds))
	}
	var addresses []*solana.AccountMeta
	for _, publicKeyMeta := range publicKeys {
		address, _, err := solana.FindProgramAddress(seeds, publicKeyMeta.PublicKey)
		if err != nil {
			return nil, fmt.Errorf("error finding program address: %w", err)
		}
		addresses = append(addresses, &solana.AccountMeta{
			PublicKey:  address,
			IsSigner:   lookup.IsSigner,
			IsWritable: lookup.IsWritable,
		})
	}
	return addresses, nil
}

func (s *SolanaChainWriterService) ResolveLookupTables(ctx context.Context, args any, lookupTables LookupTables) (map[string]map[string][]*solana.AccountMeta, map[solana.PublicKey]solana.PublicKeySlice, error) {
	derivedTableMap := make(map[string]map[string][]*solana.AccountMeta)
	staticTableMap := make(map[solana.PublicKey]solana.PublicKeySlice)

	// Read derived lookup tables
	for _, derivedLookup := range lookupTables.DerivedLookupTables {
		// Load the lookup table - note: This could be multiple tables if the lookup is a PDALookups that resovles to more
		// than one address
		lookupTableMap, _, err := s.LoadTable(ctx, args, derivedLookup, s.reader, derivedTableMap)
		if err != nil {
			return nil, nil, fmt.Errorf("error loading derived lookup table: %w", err)
		}

		// Merge the loaded table map into the result
		for tableName, innerMap := range lookupTableMap {
			if derivedTableMap[tableName] == nil {
				derivedTableMap[tableName] = make(map[string][]*solana.AccountMeta)
			}
			for accountKey, metas := range innerMap {
				derivedTableMap[tableName][accountKey] = metas
			}
		}
	}

	// Read static lookup tables
	for _, staticTable := range lookupTables.StaticLookupTables {
		addressses, err := getLookupTableAddresses(ctx, s.reader, staticTable)
		if err != nil {
			return nil, nil, fmt.Errorf("error fetching static lookup table address: %w", err)
		}
		staticTableMap[staticTable] = addressses
	}

	return derivedTableMap, staticTableMap, nil
}

func (s *SolanaChainWriterService) LoadTable(ctx context.Context, args any, rlt DerivedLookupTable, reader client.Reader, derivedTableMap map[string]map[string][]*solana.AccountMeta) (map[string]map[string][]*solana.AccountMeta, []*solana.AccountMeta, error) {
	// Resolve all addresses specified by the identifier
	lookupTableAddresses, err := GetAddresses(ctx, args, []Lookup{rlt.Accounts}, nil, reader)
	if err != nil {
		return nil, nil, fmt.Errorf("error resolving addresses for lookup table: %w", err)
	}

	// Nested map in case the lookup table resolves to multiple addresses
	resultMap := make(map[string]map[string][]*solana.AccountMeta)
	var lookupTableMetas []*solana.AccountMeta

	// Iterate over each address of the lookup table
	for _, addressMeta := range lookupTableAddresses {
		// Read the full list of addresses from the lookup table
		addresses, err := getLookupTableAddresses(ctx, reader, addressMeta.PublicKey)
		if err != nil {
			return nil, nil, fmt.Errorf("error fetching lookup table address: %s, error: %w", addressMeta.PublicKey, err)
		}

		// Create the inner map for this lookup table
		if resultMap[rlt.Name] == nil {
			resultMap[rlt.Name] = make(map[string][]*solana.AccountMeta)
		}

		// Populate the inner map (keyed by the account public key)
		for _, addr := range addresses {
			resultMap[rlt.Name][addressMeta.PublicKey.String()] = append(resultMap[rlt.Name][addressMeta.PublicKey.String()], &solana.AccountMeta{
				PublicKey:  addr,
				IsSigner:   addressMeta.IsSigner,
				IsWritable: addressMeta.IsWritable,
			})
		}

		// Add the current lookup table address to the list of metas
		lookupTableMetas = append(lookupTableMetas, addressMeta)
	}

	return resultMap, lookupTableMetas, nil
}

func getLookupTableAddresses(ctx context.Context, reader client.Reader, tableAddress solana.PublicKey) (solana.PublicKeySlice, error) {
	// Fetch the account info for the static table
	accountInfo, err := reader.GetAccountInfoWithOpts(ctx, tableAddress, &rpc.GetAccountInfoOpts{
		Encoding:   "base64",
		Commitment: rpc.CommitmentFinalized,
	})

	if err != nil || accountInfo == nil || accountInfo.Value == nil {
		return nil, fmt.Errorf("error fetching account info for table: %s, error: %w", tableAddress.String(), err)
	}
	alt, err := addresslookuptable.DecodeAddressLookupTableState(accountInfo.GetBinary())
	if err != nil {
		return nil, fmt.Errorf("error decoding address lookup table state: %w", err)
	}
	return alt.Addresses, nil
}
