package chainwriter

import (
	"context"
	"fmt"

	"github.com/gagliardetto/solana-go"
	addresslookuptable "github.com/gagliardetto/solana-go/programs/address-lookup-table"
	"github.com/gagliardetto/solana-go/rpc"
	"github.com/smartcontractkit/chainlink-solana/pkg/solana/client"
)

type Lookup interface {
	Resolve(ctx context.Context, args any, derivedTableMap map[string]map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error)
}

// AccountConstant represents a fixed address, provided in Base58 format, converted into a `solana.PublicKey`.
type AccountConstant struct {
	Name       string
	Address    string
	IsSigner   bool
	IsWritable bool
}

// AccountLookup dynamically derives an account address from args using a specified location path.
type AccountLookup struct {
	Name       string
	Location   string
	IsSigner   bool
	IsWritable bool
}

// PDALookups generates Program Derived Addresses (PDA) by combining a derived public key with one or more seeds.
type PDALookups struct {
	Name string
	// The public key of the PDA to be combined with seeds. If there are multiple PublicKeys
	// there will be multiple PDAs generated by combining each PublicKey with the seeds.
	PublicKey Lookup
	// Seeds to be derived from an additional lookup
	Seeds      []Lookup
	IsSigner   bool
	IsWritable bool
}

type ValueLookup struct {
	Location string
}

// LookupTables represents a list of lookup tables that are used to derive addresses for a program.
type LookupTables struct {
	DerivedLookupTables []DerivedLookupTable
	StaticLookupTables  []string
}

// DerivedLookupTable represents a lookup table that is used to derive addresses for a program.
type DerivedLookupTable struct {
	Name     string
	Accounts Lookup
}

// AccountsFromLookupTable extracts accounts from a lookup table that was previously read and stored in memory.
type AccountsFromLookupTable struct {
	LookupTablesName string
	IncludeIndexes   []int
}

func (ac AccountConstant) Resolve(_ context.Context, _ any, _ map[string]map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error) {
	address, err := solana.PublicKeyFromBase58(ac.Address)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error getting account from constant: %w", err), debugID)
	}
	return []*solana.AccountMeta{
		{
			PublicKey:  address,
			IsSigner:   ac.IsSigner,
			IsWritable: ac.IsWritable,
		},
	}, nil
}

func (al AccountLookup) Resolve(_ context.Context, args any, _ map[string]map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error) {
	derivedAddresses, err := GetAddressAtLocation(args, al.Location, debugID)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error getting account from lookup: %w", err), debugID)
	}

	var metas []*solana.AccountMeta
	for _, address := range derivedAddresses {
		metas = append(metas, &solana.AccountMeta{
			PublicKey:  address,
			IsSigner:   al.IsSigner,
			IsWritable: al.IsWritable,
		})
	}
	return metas, nil
}

func (alt AccountsFromLookupTable) Resolve(_ context.Context, _ any, derivedTableMap map[string]map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error) {
	// Fetch the inner map for the specified lookup table name
	innerMap, ok := derivedTableMap[alt.LookupTablesName]
	if !ok {
		return nil, errorWithDebugID(fmt.Errorf("lookup table not found: %s", alt.LookupTablesName), debugID)
	}

	var result []*solana.AccountMeta

	// If no indices are specified, include all addresses
	if len(alt.IncludeIndexes) == 0 {
		for _, metas := range innerMap {
			result = append(result, metas...)
		}
		return result, nil
	}

	// Otherwise, include only addresses at the specified indices
	for publicKey, metas := range innerMap {
		for _, index := range alt.IncludeIndexes {
			if index < 0 || index >= len(metas) {
				return nil, errorWithDebugID(fmt.Errorf("invalid index %d for account %s in lookup table %s", index, publicKey, alt.LookupTablesName), debugID)
			}
			result = append(result, metas[index])
		}
	}

	return result, nil
}

func (pda PDALookups) Resolve(ctx context.Context, args any, derivedTableMap map[string]map[string][]*solana.AccountMeta, debugID string) ([]*solana.AccountMeta, error) {
	publicKeys, err := GetAddresses(ctx, args, []Lookup{pda.PublicKey}, derivedTableMap, debugID)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error getting public key for PDALookups: %w", err), debugID)
	}

	seeds, err := getSeedBytes(ctx, pda, args, derivedTableMap, debugID)
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error getting seeds for PDALookups: %w", err), debugID)
	}

	return generatePDAs(publicKeys, seeds, pda, debugID)
}

// getSeedBytes extracts the seeds for the PDALookups.
// It handles both AddressSeeds (which are public keys) and ValueSeeds (which are byte arrays from input args).
func getSeedBytes(ctx context.Context, lookup PDALookups, args any, derivedTableMap map[string]map[string][]*solana.AccountMeta, debugID string) ([][]byte, error) {
	var seedBytes [][]byte

	// Process AddressSeeds first (e.g., public keys)
	for _, seed := range lookup.Seeds {
		// Get the address(es) at the seed location
		seedAddresses, err := GetAddresses(ctx, args, []Lookup{seed}, derivedTableMap, debugID)
		if err != nil {
			return nil, errorWithDebugID(fmt.Errorf("error getting address seed: %w", err), debugID)
		}

		// Add each address seed as bytes
		for _, address := range seedAddresses {
			seedBytes = append(seedBytes, address.PublicKey.Bytes())
		}
	}

	return seedBytes, nil
}

// generatePDAs generates program-derived addresses (PDAs) from public keys and seeds.
func generatePDAs(publicKeys []*solana.AccountMeta, seeds [][]byte, lookup PDALookups, debugID string) ([]*solana.AccountMeta, error) {
	if len(seeds) > 1 && len(publicKeys) > 1 {
		return nil, errorWithDebugID(fmt.Errorf("multiple public keys and multiple seeds are not allowed"), debugID)
	}

	var addresses []*solana.AccountMeta
	for _, publicKeyMeta := range publicKeys {
		address, _, err := solana.FindProgramAddress(seeds, publicKeyMeta.PublicKey)
		if err != nil {
			return nil, errorWithDebugID(fmt.Errorf("error finding program address: %w", err), debugID)
		}
		addresses = append(addresses, &solana.AccountMeta{
			PublicKey:  address,
			IsSigner:   lookup.IsSigner,
			IsWritable: lookup.IsWritable,
		})
	}
	return addresses, nil
}

func (s *SolanaChainWriterService) ResolveLookupTables(ctx context.Context, args any, lookupTables LookupTables, debugID string) (map[string]map[string][]*solana.AccountMeta, map[solana.PublicKey]solana.PublicKeySlice, error) {
	derivedTableMap := make(map[string]map[string][]*solana.AccountMeta)
	staticTableMap := make(map[solana.PublicKey]solana.PublicKeySlice)

	// Read derived lookup tables
	for _, derivedLookup := range lookupTables.DerivedLookupTables {
		lookupTableMap, _, err := s.LoadTable(ctx, args, derivedLookup, s.reader, derivedTableMap, debugID)
		if err != nil {
			return nil, nil, errorWithDebugID(fmt.Errorf("error loading derived lookup table: %w", err), debugID)
		}

		// Merge the loaded table map into the result
		for tableName, innerMap := range lookupTableMap {
			if derivedTableMap[tableName] == nil {
				derivedTableMap[tableName] = make(map[string][]*solana.AccountMeta)
			}
			for accountKey, metas := range innerMap {
				derivedTableMap[tableName][accountKey] = metas
			}
		}
	}

	// Read static lookup tables
	for _, staticTable := range lookupTables.StaticLookupTables {
		// Parse the static table address
		tableAddress, err := solana.PublicKeyFromBase58(staticTable)
		if err != nil {
			return nil, nil, errorWithDebugID(fmt.Errorf("invalid static lookup table address: %s, error: %w", staticTable, err), debugID)
		}

		addressses, err := getLookupTableAddress(ctx, s.reader, tableAddress, debugID)
		staticTableMap[tableAddress] = addressses
	}

	return derivedTableMap, staticTableMap, nil
}

func (s *SolanaChainWriterService) LoadTable(ctx context.Context, args any, rlt DerivedLookupTable, reader client.Reader, derivedTableMap map[string]map[string][]*solana.AccountMeta, debugID string) (map[string]map[string][]*solana.AccountMeta, []*solana.AccountMeta, error) {
	// Resolve all addresses specified by the identifier
	lookupTableAddresses, err := GetAddresses(ctx, args, []Lookup{rlt.Accounts}, nil, debugID)
	if err != nil {
		return nil, nil, errorWithDebugID(fmt.Errorf("error resolving addresses for lookup table: %w", err), debugID)
	}

	resultMap := make(map[string]map[string][]*solana.AccountMeta)
	var lookupTableMetas []*solana.AccountMeta

	// Iterate over each address of the lookup table
	for _, addressMeta := range lookupTableAddresses {
		// Fetch account info
		addresses, err := getLookupTableAddress(ctx, reader, addressMeta.PublicKey, debugID)
		if err != nil {
			return nil, nil, errorWithDebugID(fmt.Errorf("error fetching lookup table address: %w", err), debugID)
		}

		// Create the inner map for this lookup table
		if resultMap[rlt.Name] == nil {
			resultMap[rlt.Name] = make(map[string][]*solana.AccountMeta)
		}

		// Populate the inner map (keyed by the account public key)
		for _, addr := range addresses {
			resultMap[rlt.Name][addressMeta.PublicKey.String()] = append(resultMap[rlt.Name][addressMeta.PublicKey.String()], &solana.AccountMeta{
				PublicKey:  addr,
				IsSigner:   false,
				IsWritable: false,
			})
		}

		// Add the current lookup table address to the list of metas
		lookupTableMetas = append(lookupTableMetas, addressMeta)
	}

	return resultMap, lookupTableMetas, nil
}

func getLookupTableAddress(ctx context.Context, reader client.Reader, tableAddress solana.PublicKey, debugID string) (solana.PublicKeySlice, error) {
	// Fetch the account info for the static table
	accountInfo, err := reader.GetAccountInfoWithOpts(ctx, tableAddress, &rpc.GetAccountInfoOpts{
		Encoding:   "base64",
		Commitment: rpc.CommitmentConfirmed,
	})

	if err != nil || accountInfo == nil || accountInfo.Value == nil {
		return nil, errorWithDebugID(fmt.Errorf("error fetching account info for table: %s, error: %w", tableAddress.String(), err), debugID)
	}
	alt, err := addresslookuptable.DecodeAddressLookupTableState(accountInfo.GetBinary())
	if err != nil {
		return nil, errorWithDebugID(fmt.Errorf("error decoding address lookup table state: %w", err), debugID)
	}
	return alt.Addresses, nil
}
