package chainwriter

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"

	"github.com/gagliardetto/solana-go"
	"github.com/gagliardetto/solana-go/rpc"

	"github.com/smartcontractkit/chainlink-solana/pkg/solana/client"
	solcommoncodec "github.com/smartcontractkit/chainlink-solana/pkg/solana/codec/common"
	codecv1 "github.com/smartcontractkit/chainlink-solana/pkg/solana/codec/v1"
)

var (
	ErrLookupNotFoundAtLocation = fmt.Errorf("error getting account from lookup")
	ErrLookupTableNotFound      = fmt.Errorf("lookup table not found")
	ErrGettingSeedAtLocation    = fmt.Errorf("error getting address seed for location")
)

type Lookup struct {
	Optional                bool
	AccountConstant         *AccountConstant         `json:"accountConstant,omitempty"`
	AccountLookup           *AccountLookup           `json:"accountLookup,omitempty"`
	PDALookups              *PDALookups              `json:"pdas,omitempty"`
	AccountsFromLookupTable *AccountsFromLookupTable `json:"accountsFromLookupTable,omitempty"`
}

// AccountConstant represents a fixed address, provided in Base58 format, converted into a `solana.PublicKey`.
type AccountConstant struct {
	Name       string `json:"name,omitempty"`
	Address    string `json:"address"`
	IsSigner   bool   `json:"isSigner,omitempty"`
	IsWritable bool   `json:"isWritable,omitempty"`
}

// AccountLookup dynamically derives an account address from args using a specified location path.
type AccountLookup struct {
	Name     string `json:"name,omitempty"`
	Location string `json:"location"`
	// IsSigner and IsWritable can either be a constant bool or a location to a bitmap which decides the bools
	IsSigner   MetaBool `json:"isSigner,omitempty"`
	IsWritable MetaBool `json:"isWritable,omitempty"`
}

type MetaBool struct {
	Value          bool   `json:"value,omitempty"`          // bool value
	BitmapLocation string `json:"bitmapLocation,omitempty"` // dot separated location of the bitmap
}

type Seed struct {
	Static  []byte `json:"static,omitempty"`  // Static seed value
	Dynamic Lookup `json:"dynamic,omitempty"` // Dynamic lookup for seed
}

// PDALookups generates Program Derived Addresses (PDA) by combining a derived public key with one or more seeds.
type PDALookups struct {
	Name string `json:"name,omitempty"`
	// The public key of the PDA to be combined with seeds. If there are multiple PublicKeys
	// there will be multiple PDAs generated by combining each PublicKey with the seeds.
	PublicKey Lookup `json:"publicKey"`
	// Seeds to be derived from an additional lookup
	Seeds      []Seed `json:"seeds"`
	IsSigner   bool   `json:"isSigner,omitempty"`
	IsWritable bool   `json:"isWritable,omitempty"`
	// OPTIONAL: On-chain location and type of desired data from PDA (e.g. a sub-account of the data account)
	InternalField InternalField `json:"internalField,omitempty"`
}

type InternalField struct {
	// must map directly to IDL type
	TypeName string `json:"typeName"`
	Location string `json:"location"`
	IDL      string `json:"idl"`
}

// LookupTables represents a list of lookup tables that are used to derive addresses for a program.
type LookupTables struct {
	DerivedLookupTables []DerivedLookupTable `json:"derivedLookupTables,omitempty"`
	StaticLookupTables  []solana.PublicKey   `json:"staticLookupTables,omitempty"`
}

// DerivedLookupTable represents a lookup table that is used to derive addresses for a program.
type DerivedLookupTable struct {
	Name     string `json:"name,omitempty"`
	Accounts Lookup `json:"accounts"`
	Optional bool   `json:"optional"`
}

// AccountsFromLookupTable extracts accounts from a lookup table that was previously read and stored in memory.
type AccountsFromLookupTable struct {
	LookupTableName string `json:"lookupTableName"`
	IncludeIndexes  []int  `json:"includeIndexes"`
}

type ATALookup struct {
	// Field that determines whether the ATA lookup is necessary. Basically
	// just need to check this field exists. Dot separated location.
	Location string
	// If the field exists, initialize a ATA account using the Wallet, Token Program, and Mint addresses below
	WalletAddress Lookup
	TokenProgram  Lookup // Deprecated: The token program is now fetched from the mint account
	MintAddress   Lookup
	Optional      bool
}

func (l Lookup) validate() error {
	count := 0
	for _, v := range []bool{l.AccountConstant != nil, l.AccountLookup != nil, l.PDALookups != nil, l.AccountsFromLookupTable != nil} {
		if v {
			count++
		}
	}
	if count != 1 {
		return fmt.Errorf("exactly one of AccountConstant, AccountLookup, PDALookups, or AccountsFromLookupTable must be specified, got %d", count)
	}
	return nil
}

func (l Lookup) Resolve(ctx context.Context, args any, derivedTableMap map[string]map[string][]*solana.AccountMeta, client client.MultiClient) ([]*solana.AccountMeta, error) {
	// could update this in the future to validate the entire config at initialization time recursively.
	err := l.validate()
	if err != nil {
		return nil, err
	}
	if l.AccountConstant != nil {
		return l.AccountConstant.Resolve()
	} else if l.AccountLookup != nil {
		return l.AccountLookup.Resolve(args)
	} else if l.PDALookups != nil {
		return l.PDALookups.Resolve(ctx, args, derivedTableMap, client)
	} else if l.AccountsFromLookupTable != nil {
		return l.AccountsFromLookupTable.Resolve(derivedTableMap)
	}
	return nil, fmt.Errorf("no lookup type specified")
}

func (ac AccountConstant) Resolve() ([]*solana.AccountMeta, error) {
	address, err := solana.PublicKeyFromBase58(ac.Address)
	if err != nil {
		return nil, lookupErrWithName(ac.Name, fmt.Errorf("error getting account from constant: %w", err))
	}
	return []*solana.AccountMeta{
		{
			PublicKey:  address,
			IsSigner:   ac.IsSigner,
			IsWritable: ac.IsWritable,
		},
	}, nil
}

func (al AccountLookup) Resolve(args any) ([]*solana.AccountMeta, error) {
	derivedValues, err := GetValuesAtLocation(args, al.Location)
	if err != nil {
		return nil, lookupErrWithName(al.Name, fmt.Errorf("%w: %v", ErrLookupNotFoundAtLocation, err))
	}

	if len(derivedValues) == 0 {
		// early return, there's nothing to set
		return nil, nil
	}

	var metas []*solana.AccountMeta
	signerIndexes, err := resolveBitMap(al.IsSigner, args, len(derivedValues))
	if err != nil {
		return nil, lookupErrWithName(al.Name, fmt.Errorf("failed to resolve signer bit map: %w", err))
	}

	writerIndexes, err := resolveBitMap(al.IsWritable, args, len(derivedValues))
	if err != nil {
		return nil, lookupErrWithName(al.Name, fmt.Errorf("failed to resolve writer bit map: %w", err))
	}

	for i, address := range derivedValues {
		// Resolve isSigner for this particular pubkey
		isSigner := signerIndexes[i]

		// Resolve isWritable for this particular pubkey
		isWritable := writerIndexes[i]

		metas = append(metas, &solana.AccountMeta{
			PublicKey:  solana.PublicKeyFromBytes(address),
			IsSigner:   isSigner,
			IsWritable: isWritable,
		})
	}
	return metas, nil
}

func resolveBitMap(mb MetaBool, args any, length int) ([]bool, error) {
	if length > 64 {
		return []bool{}, fmt.Errorf("bitmap cannot have more than 64 flags. provided length: %d", length)
	}
	result := make([]bool, length)
	if mb.BitmapLocation == "" {
		for i := 0; i < length; i++ {
			result[i] = mb.Value
		}
		return result, nil
	}

	bitmapVals, err := GetValuesAtLocation(args, mb.BitmapLocation)
	if err != nil {
		return []bool{}, fmt.Errorf("error reading bitmap from location '%s': %w", mb.BitmapLocation, err)
	}

	if len(bitmapVals) != 1 {
		return []bool{}, fmt.Errorf("bitmap value is not a single value: %v, length: %d", bitmapVals, len(bitmapVals))
	}

	if len(bitmapVals[0]) != 8 {
		return []bool{}, fmt.Errorf("bitmap value has insufficient bytes: %v, length: %d", bitmapVals[0], len(bitmapVals[0]))
	}

	// The bitmap is user defined and always uint64 size. The input cannot be further validated for correctness.
	bitmapInt := binary.LittleEndian.Uint64(bitmapVals[0])
	for i := 0; i < length; i++ {
		result[i] = bitmapInt&(1<<i) > 0
	}

	return result, nil
}

func (alt AccountsFromLookupTable) Resolve(derivedTableMap map[string]map[string][]*solana.AccountMeta) ([]*solana.AccountMeta, error) {
	// Fetch the inner map for the specified lookup table name
	innerMap, ok := derivedTableMap[alt.LookupTableName]
	if !ok {
		return nil, fmt.Errorf("%w: %s", ErrLookupTableNotFound, alt.LookupTableName)
	}

	var result []*solana.AccountMeta

	// If no indices are specified, include all addresses
	if len(alt.IncludeIndexes) == 0 {
		for _, metas := range innerMap {
			result = append(result, metas...)
		}
		return result, nil
	}

	// Otherwise, include only addresses at the specified indices
	for publicKey, metas := range innerMap {
		for _, index := range alt.IncludeIndexes {
			if index < 0 || index >= len(metas) {
				return nil, lookupErrWithName(alt.LookupTableName, fmt.Errorf("invalid index %d for account %s", index, publicKey))
			}
			result = append(result, metas[index])
		}
	}

	return result, nil
}

func (pda PDALookups) Resolve(ctx context.Context, args any, derivedTableMap map[string]map[string][]*solana.AccountMeta, client client.MultiClient) ([]*solana.AccountMeta, error) {
	publicKeys, err := GetAddresses(ctx, args, []Lookup{pda.PublicKey}, derivedTableMap, client)
	if err != nil {
		return nil, lookupErrWithName(pda.Name, fmt.Errorf("error getting public key for PDALookups: %w", err))
	}

	seeds, err := getSeedBytesCombinations(ctx, pda, args, derivedTableMap, client)
	if err != nil {
		return nil, lookupErrWithName(pda.Name, fmt.Errorf("error getting seeds for PDALookups: %w", err))
	}

	pdas, err := generatePDAs(publicKeys, seeds, pda)
	if err != nil {
		return nil, lookupErrWithName(pda.Name, fmt.Errorf("error generating PDAs: %w", err))
	}

	if pda.InternalField.Location == "" {
		return pdas, nil
	}

	// If a decoded location is specified, fetch the data at that location
	var result []*solana.AccountMeta
	for _, accountMeta := range pdas {
		accountInfo, err := client.GetAccountInfoWithOpts(ctx, accountMeta.PublicKey, &rpc.GetAccountInfoOpts{
			Encoding:   "base64",
			Commitment: rpc.CommitmentFinalized,
		})

		if err != nil || accountInfo == nil || accountInfo.Value == nil || accountInfo.Value.Data == nil {
			return nil, lookupErrWithName(pda.Name, fmt.Errorf("error fetching account info for PDA account: %s, error: %w", accountMeta.PublicKey.String(), err))
		}

		var idlCodec codecv1.IDL
		if err = json.Unmarshal([]byte(pda.InternalField.IDL), &idlCodec); err != nil {
			return nil, lookupErrWithName(pda.Name, fmt.Errorf("failed to unmarshal IDL: %w", err))
		}

		internalType := pda.InternalField.TypeName

		idlDef, err := codecv1.FindDefinitionFromIDL(solcommoncodec.ChainConfigTypeAccountDef, internalType, idlCodec)
		if err != nil {
			return nil, lookupErrWithName(pda.Name, fmt.Errorf("error finding definition for type %s: %w", internalType, err))
		}

		input, err := codecv1.CreateCodecEntry(idlDef, internalType, idlCodec, nil)
		if err != nil {
			return nil, lookupErrWithName(pda.Name, fmt.Errorf("failed to create codec entry for type %s, error: %w", internalType, err))
		}

		decoded, _, err := input.Decode(accountInfo.Value.Data.GetBinary())
		if err != nil {
			return nil, lookupErrWithName(pda.Name, fmt.Errorf("error decoding account data: %w", err))
		}

		value, err := GetValuesAtLocation(decoded, pda.InternalField.Location)
		if err != nil {
			return nil, lookupErrWithName(pda.Name, fmt.Errorf("error getting value at location %s: %w", pda.InternalField.Location, err))
		}
		if len(value) > 1 {
			return nil, lookupErrWithName(pda.Name, fmt.Errorf("multiple values found at location %s", pda.InternalField.Location))
		}

		result = append(result, &solana.AccountMeta{
			PublicKey:  solana.PublicKeyFromBytes(value[0]),
			IsSigner:   accountMeta.IsSigner,
			IsWritable: accountMeta.IsWritable,
		})
	}
	return result, nil
}

// getSeedBytesCombinations extracts the seeds for the PDALookups.
// The return type is [][][]byte, where each element of the outer slice is
// one combination of seeds. This handles the case where one seed can resolve
// to multiple addresses, multiplying the combinations accordingly.
func getSeedBytesCombinations(
	ctx context.Context,
	lookup PDALookups,
	args any,
	derivedTableMap map[string]map[string][]*solana.AccountMeta,
	client client.MultiClient,
) ([][][]byte, error) {
	allCombinations := [][][]byte{
		{},
	}

	// For each seed in the definition, expand the current list of combinations
	// by all possible values for this seed.
	for _, seed := range lookup.Seeds {
		expansions := make([][]byte, 0)
		if seed.Static != nil {
			expansions = append(expansions, seed.Static)
			// Static and Dynamic seeds are mutually exclusive
		} else if !seed.Dynamic.IsNil() {
			dynamicSeed := seed.Dynamic
			if dynamicSeed.AccountLookup != nil {
				lookupSeed := dynamicSeed.AccountLookup
				// Get value from a location (This doesn't have to be an address, it can be any value)
				bytes, err := GetValuesAtLocation(args, lookupSeed.Location)
				if err != nil {
					return nil, fmt.Errorf("%w %q: %w", ErrGettingSeedAtLocation, lookupSeed.Location, err)
				}
				// append each byte array to the expansions
				for _, b := range bytes {
					// validate seed length
					if len(b) > solana.MaxSeedLength {
						return nil, fmt.Errorf("seed byte array exceeds maximum length of %d: got %d bytes", solana.MaxSeedLength, len(b))
					}
					expansions = append(expansions, b)
				}
			} else {
				// Get address seeds from the lookup
				seedAddresses, err := GetAddresses(ctx, args, []Lookup{dynamicSeed}, derivedTableMap, client)
				if err != nil {
					return nil, fmt.Errorf("error getting address seed: %w", err)
				}
				// Add each address seed to the expansions
				for _, addrMeta := range seedAddresses {
					b := addrMeta.PublicKey.Bytes()
					if len(b) > solana.MaxSeedLength {
						return nil, fmt.Errorf("seed byte array exceeds maximum length of %d: got %d bytes", solana.MaxSeedLength, len(b))
					}
					expansions = append(expansions, b)
				}
			}
		}

		// expansions is the list of possible seed bytes for this single seed lookup.
		// Multiply the existing combinations in allCombinations by each item in expansions.
		newCombinations := make([][][]byte, 0, len(allCombinations)*len(expansions))
		for _, existingCombo := range allCombinations {
			for _, expandedSeed := range expansions {
				comboCopy := make([][]byte, len(existingCombo)+1)
				copy(comboCopy, existingCombo)
				comboCopy[len(existingCombo)] = expandedSeed
				newCombinations = append(newCombinations, comboCopy)
			}
		}

		allCombinations = newCombinations
	}

	return allCombinations, nil
}

func (l Lookup) IsNil() bool {
	return l.AccountConstant == nil && l.AccountLookup == nil && l.PDALookups == nil && l.AccountsFromLookupTable == nil
}

// generatePDAs generates program-derived addresses (PDAs) from public keys and seeds.
// it will result in a list of PDAs whose length is the product of the number of public keys
// and the number of seed combinations.
func generatePDAs(
	publicKeys []*solana.AccountMeta,
	seedCombos [][][]byte,
	lookup PDALookups,
) ([]*solana.AccountMeta, error) {
	var results []*solana.AccountMeta
	for _, publicKeyMeta := range publicKeys {
		for _, combo := range seedCombos {
			if len(combo) > solana.MaxSeeds {
				return nil, fmt.Errorf("seed maximum exceeded: %d", len(combo))
			}
			address, _, err := solana.FindProgramAddress(combo, publicKeyMeta.PublicKey)
			if err != nil {
				return nil, fmt.Errorf("error finding program address: %w", err)
			}
			results = append(results, &solana.AccountMeta{
				PublicKey:  address,
				IsSigner:   lookup.IsSigner,
				IsWritable: lookup.IsWritable,
			})
		}
	}

	return results, nil
}

func lookupErrWithName(name string, err error) error {
	return fmt.Errorf("lookup: %s, err: %w", name, err)
}
