self-hosted-runner:
  # Labels of self-hosted or large runner labels in array of string
  labels:
    - ubuntu-latest-4cores-16GB
    - ubuntu-latest-8cores-32GB
    - ubuntu-latest-16cores-64GB
    - ubuntu-latest-32cores-128GB
    - ubuntu-latest-64cores-256GB
