version: 2
updates:
  - package-ecosystem: gomod
    directory: "/lib"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ctf"
  - package-ecosystem: gomod
    directory: "/wasp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ctf"
  - package-ecosystem: gomod
    directory: "/seth"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ctf"
  - package-ecosystem: gomod
    directory: "/havoc"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ctf"
  - package-ecosystem: gomod
    directory: "/k8s-test-runner"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ctf"
