// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	solana "github.com/gagliardetto/solana-go"
)

// TxManager is an autogenerated mock type for the TxManager type
type TxManager struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: accountID, msg
func (_m *TxManager) Enqueue(accountID string, msg *solana.Transaction) error {
	ret := _m.Called(accountID, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *solana.Transaction) error); ok {
		r0 = rf(accountID, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTxManager creates a new instance of TxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxManager {
	mock := &TxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
