// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package test_item_type

import (
	"fmt"

	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type TestItem struct {
	Field               int32
	OracleId            uint8
	OracleIds           [32]uint8
	AccountStruct       AccountStruct
	Accounts            []ag_solanago.PublicKey
	DifferentField      string
	BigField            ag_binary.Int128
	NestedDynamicStruct NestedDynamic
	NestedStaticStruct  NestedStatic
}

var TestItemDiscriminator = [8]byte{148, 105, 105, 155, 26, 167, 212, 149}

func (obj TestItem) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(TestItemDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Field` param:
	err = encoder.Encode(obj.Field)
	if err != nil {
		return err
	}
	// Serialize `OracleId` param:
	err = encoder.Encode(obj.OracleId)
	if err != nil {
		return err
	}
	// Serialize `OracleIds` param:
	err = encoder.Encode(obj.OracleIds)
	if err != nil {
		return err
	}
	// Serialize `AccountStruct` param:
	err = encoder.Encode(obj.AccountStruct)
	if err != nil {
		return err
	}
	// Serialize `Accounts` param:
	err = encoder.Encode(obj.Accounts)
	if err != nil {
		return err
	}
	// Serialize `DifferentField` param:
	err = encoder.Encode(obj.DifferentField)
	if err != nil {
		return err
	}
	// Serialize `BigField` param:
	err = encoder.Encode(obj.BigField)
	if err != nil {
		return err
	}
	// Serialize `NestedDynamicStruct` param:
	err = encoder.Encode(obj.NestedDynamicStruct)
	if err != nil {
		return err
	}
	// Serialize `NestedStaticStruct` param:
	err = encoder.Encode(obj.NestedStaticStruct)
	if err != nil {
		return err
	}
	return nil
}

func (obj *TestItem) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(TestItemDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[148 105 105 155 26 167 212 149]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Field`:
	err = decoder.Decode(&obj.Field)
	if err != nil {
		return err
	}
	// Deserialize `OracleId`:
	err = decoder.Decode(&obj.OracleId)
	if err != nil {
		return err
	}
	// Deserialize `OracleIds`:
	err = decoder.Decode(&obj.OracleIds)
	if err != nil {
		return err
	}
	// Deserialize `AccountStruct`:
	err = decoder.Decode(&obj.AccountStruct)
	if err != nil {
		return err
	}
	// Deserialize `Accounts`:
	err = decoder.Decode(&obj.Accounts)
	if err != nil {
		return err
	}
	// Deserialize `DifferentField`:
	err = decoder.Decode(&obj.DifferentField)
	if err != nil {
		return err
	}
	// Deserialize `BigField`:
	err = decoder.Decode(&obj.BigField)
	if err != nil {
		return err
	}
	// Deserialize `NestedDynamicStruct`:
	err = decoder.Decode(&obj.NestedDynamicStruct)
	if err != nil {
		return err
	}
	// Deserialize `NestedStaticStruct`:
	err = decoder.Decode(&obj.NestedStaticStruct)
	if err != nil {
		return err
	}
	return nil
}
