// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package test_item_type

import (
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type AccountStruct struct {
	Account    ag_solanago.PublicKey
	AccountStr ag_solanago.PublicKey
}

func (obj AccountStruct) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Account` param:
	err = encoder.Encode(obj.Account)
	if err != nil {
		return err
	}
	// Serialize `AccountStr` param:
	err = encoder.Encode(obj.AccountStr)
	if err != nil {
		return err
	}
	return nil
}

func (obj *AccountStruct) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Account`:
	err = decoder.Decode(&obj.Account)
	if err != nil {
		return err
	}
	// Deserialize `AccountStr`:
	err = decoder.Decode(&obj.AccountStr)
	if err != nil {
		return err
	}
	return nil
}

type InnerDynamic struct {
	IntVal int64
	S      string
}

func (obj InnerDynamic) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `IntVal` param:
	err = encoder.Encode(obj.IntVal)
	if err != nil {
		return err
	}
	// Serialize `S` param:
	err = encoder.Encode(obj.S)
	if err != nil {
		return err
	}
	return nil
}

func (obj *InnerDynamic) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `IntVal`:
	err = decoder.Decode(&obj.IntVal)
	if err != nil {
		return err
	}
	// Deserialize `S`:
	err = decoder.Decode(&obj.S)
	if err != nil {
		return err
	}
	return nil
}

type NestedDynamic struct {
	FixedBytes [2]uint8
	Inner      InnerDynamic
}

func (obj NestedDynamic) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `FixedBytes` param:
	err = encoder.Encode(obj.FixedBytes)
	if err != nil {
		return err
	}
	// Serialize `Inner` param:
	err = encoder.Encode(obj.Inner)
	if err != nil {
		return err
	}
	return nil
}

func (obj *NestedDynamic) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `FixedBytes`:
	err = decoder.Decode(&obj.FixedBytes)
	if err != nil {
		return err
	}
	// Deserialize `Inner`:
	err = decoder.Decode(&obj.Inner)
	if err != nil {
		return err
	}
	return nil
}

type InnerStatic struct {
	IntVal int64
	A      ag_solanago.PublicKey
}

func (obj InnerStatic) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `IntVal` param:
	err = encoder.Encode(obj.IntVal)
	if err != nil {
		return err
	}
	// Serialize `A` param:
	err = encoder.Encode(obj.A)
	if err != nil {
		return err
	}
	return nil
}

func (obj *InnerStatic) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `IntVal`:
	err = decoder.Decode(&obj.IntVal)
	if err != nil {
		return err
	}
	// Deserialize `A`:
	err = decoder.Decode(&obj.A)
	if err != nil {
		return err
	}
	return nil
}

type NestedStatic struct {
	FixedBytes [2]uint8
	Inner      InnerStatic
}

func (obj NestedStatic) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `FixedBytes` param:
	err = encoder.Encode(obj.FixedBytes)
	if err != nil {
		return err
	}
	// Serialize `Inner` param:
	err = encoder.Encode(obj.Inner)
	if err != nil {
		return err
	}
	return nil
}

func (obj *NestedStatic) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `FixedBytes`:
	err = decoder.Decode(&obj.FixedBytes)
	if err != nil {
		return err
	}
	// Deserialize `Inner`:
	err = decoder.Decode(&obj.Inner)
	if err != nil {
		return err
	}
	return nil
}
