# This is the default configuration so OCR2 tests can run without issues
[ChainlinkImage]
image="public.ecr.aws/chainlink/chainlink"
version="2.9.0"

[Logging]
test_log_collect=false

[Logging.LogStream]
log_targets=["file"]
log_producer_timeout="10s"
log_producer_retry_limit=10

####################################################################################
# TODO - Workaround due to lack of non-evm support in CTF and core
[Network]
selected_networks=["SIMULATED"]

[Network.RpcHttpUrls]
simulated = ["http://127.0.0.1"]

[Network.RpcWsUrls]
simulated = ["wss://127.0.0.1"]

####################################################################################

# Testnet program ID's
[SolanaConfig]
ocr2_program_id = "cjg3oHmg9uuPsP8D6g29NWvhySJkdYdAo9D25PRbKXJ"
access_controller_program_id = "9xi644bRR8birboDGdTiwBq3C7VEeR7VuamRYYXCubUW"
store_program_id = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
link_token_address = "7CF1GrsZsny5j9JESPj98MdYVZK38RE8ZpmTEMwECK4c"
vault_address = "FdM4dnhVpFQfjPqNG6LEfzArhuGhUjtidYu89qtGwJCS"

[Common]
internal_docker_repo = "public.ecr.aws/chainlink"
inside_k8 = false 
network = "localnet"
user = "default"
stateful_db = false
devnet_image = "anzaxyz/agave:v1.18.25"

[OCR2]
node_count = 6
test_duration = "50m"
number_of_rounds = 2

[OCR2.Smoke]
enabled = true

[OCR2.Soak]
enabled = false


