# This is the default configuration so OCR2 tests can run without issues
[ChainlinkImage]
image="public.ecr.aws/chainlink/chainlink"
version="2.9.0"

[Logging]
test_log_collect=false

[Logging.LogStream]
log_targets=["file"]
log_producer_timeout="10s"
log_producer_retry_limit=10

[Network]
selected_networks=["ETHEREUM_MAINNET"] # Default config that is required from CTF

[Network.RpcHttpUrls]
ethereum_mainnet = ["http://127.0.0.1"] # Default config that is required from CTF

[Network.RpcWsUrls]
ethereum_mainnet = ["wss://127.0.0.1"] # Default config that is required from CTF

[Network.WalletKeys]
ethereum_mainnet = ["5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"] # Default config that is required from CTF

# Testnet program ID's
[SolanaConfig]
ocr2_program_id = "cjg3oHmg9uuPsP8D6g29NWvhySJkdYdAo9D25PRbKXJ"
access_controller_program_id = "9xi644bRR8birboDGdTiwBq3C7VEeR7VuamRYYXCubUW"
store_program_id = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
link_token_address = "7CF1GrsZsny5j9JESPj98MdYVZK38RE8ZpmTEMwECK4c"
vault_address = "FdM4dnhVpFQfjPqNG6LEfzArhuGhUjtidYu89qtGwJCS"
secret="thisisatestingonlysecret"

[Common]
rpc_url = "https://api.devnet.solana.com"
ws_url = "wss://api.devnet.solana.com/"
internal_docker_repo = "public.ecr.aws/chainlink"
inside_k8 = false 
network = "localnet"
user = "default"
stateful_db = false
devnet_image = "solanalabs/solana:v1.18.15"

[OCR2]
node_count = 6
test_duration = "50m"
number_of_rounds = 2

[OCR2.Smoke]
enabled = true

[OCR2.Soak]
enabled = false


