[package]
name = "chainlink_solana"
description = "Chainlink client for Solana"
version = "2.0.0"
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]
name = "chainlink_solana"

[features]
default = []

[dependencies]
solana-program = { version = "1.17.25" }
bytemuck = { version = "1.23.2", features = ["derive"] }
borsh = { version = "0.10.3" }

[dev-dependencies]
anchor-lang = "0.29.0"