name: Install gauntlet dependencies
description: A GitHub Action to get tool versions and build Gauntlet

runs:
  if: github.event_name == 'pull_request'
    run: |
      comment="$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json body -q '.body')"
      # shellcheck disable=SC2086
      core_ref="$(echo $comment | grep -oP 'core ref: \K\S+' || true)"
      if [ -n "$core_ref" ]; then
        echo "CUSTOM_CORE_REF=${core_ref}" >> "${GITHUB_ENV}"
      fi
