name: Install and build gauntlet
description: A composite action that installs and builds all the gauntlet dependencies 

tool_versions:
  name: Get the tool versions
  runs-on: ubuntu-latest
  outputs:
    nodejs_version: ${{ steps.tool-versions.outputs.nodejs_version }}
  steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - uses: smartcontractkit/tool-versions-to-env-action@v1.0.8
      id: tool-versions

gauntlet_build:
  name: Gauntlet Build
  runs-on: ubuntu-latest
  needs: [tool_versions]
  steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Setup Node ${{ needs.tool_versions.outputs.nodejs_version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ needs.tool_versions.outputs.nodejs_version }}
    - name: Install
      run: yarn --cwd ./gauntlet install --frozen-lockfile
    - name: Build
      run: yarn --cwd ./gauntlet build
    - name: Run Gauntlet
      run: yarn --cwd ./gauntlet gauntlet
