// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package test_item_slice_type

import (
	"errors"

	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"

	"github.com/smartcontractkit/chainlink-solana/pkg/solana/codec/testutils/test_item_type"
)

// TestItemSliceType is the `TestItemSliceType` instruction.
type TestItemSliceType struct {
	TestItemSliceType *[]test_item_type.TestItem

	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTestItemSliceTypeInstructionBuilder creates a new `TestItemSliceType` instruction builder.
func NewTestItemSliceTypeInstructionBuilder() *TestItemSliceType {
	nd := &TestItemSliceType{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 0),
	}
	return nd
}

// SetTestItemSliceType sets the "TestItemSliceType" parameter.
func (inst *TestItemSliceType) SetTestItemSliceType(TestItemSliceType []test_item_type.TestItem) *TestItemSliceType {
	inst.TestItemSliceType = &TestItemSliceType
	return inst
}

func (inst TestItemSliceType) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TestItemSliceType,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TestItemSliceType) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TestItemSliceType) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.TestItemSliceType == nil {
			return errors.New("TestItemSliceType parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
	}
	return nil
}

func (inst *TestItemSliceType) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TestItemSliceType")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("TestItemSliceType", *inst.TestItemSliceType))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=0]").ParentFunc(func(accountsBranch ag_treeout.Branches) {})
				})
		})
}

func (obj TestItemSliceType) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `TestItemSliceType` param:
	err = encoder.Encode(obj.TestItemSliceType)
	if err != nil {
		return err
	}
	return nil
}
func (obj *TestItemSliceType) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `TestItemSliceType`:
	err = decoder.Decode(&obj.TestItemSliceType)
	if err != nil {
		return err
	}
	return nil
}

// NewTestItemSliceTypeInstruction declares a new TestItemSliceType instruction with the provided parameters and accounts.
func NewTestItemSliceTypeInstruction(
	// Parameters:
	TestItemSliceType []test_item_type.TestItem) *TestItemSliceType {
	return NewTestItemSliceTypeInstructionBuilder().
		SetTestItemSliceType(TestItemSliceType)
}
