name: Build Contract Artifacts
description: Common builder for test contracts for automated tests
inputs:
  ref:
    required: false
    description: The chainlink-solana ref to use

runs:
  using: composite
  steps:
    - name: Install latest Git version (>= 2.18.0) for actions/checkout
      shell: bash
      run: |
        apt-get update
        apt-get install software-properties-common -y
        add-apt-repository ppa:git-core/ppa
        apt update
        apt install git -y
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        repository: smartcontractkit/chainlink-solana
        ref: ${{ inputs.ref }}
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
        check-latest: true
    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
    - name: Generate build artifacts for go bindings check
      shell: bash
      run: anchor build
      working-directory: contracts
    - name: Check generated go bindings are up to date
      shell: bash
      run: |
        go install github.com/gagliardetto/anchor-go@v0.2.3
        ./scripts/anchor-go-gen.sh
        git diff --stat --exit-code
    - name: Generate program_ids
      shell: bash
      run: ./scripts/programs-keys-gen.sh
    - name: Generate build artifacts with custom program_ids
      shell: bash
      run: anchor build
      working-directory: contracts
    - name: Upload Artifacts
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: artifacts
        path: contracts/target/deploy
