// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	logpoller "github.com/smartcontractkit/chainlink-solana/pkg/solana/logpoller"
	mock "github.com/stretchr/testify/mock"
)

// EventSaver is an autogenerated mock type for the EventSaver type
type EventSaver struct {
	mock.Mock
}

type EventSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *EventSaver) EXPECT() *EventSaver_Expecter {
	return &EventSaver_Expecter{mock: &_m.Mock}
}

// SaveEvent provides a mock function with given fields: evt
func (_m *EventSaver) SaveEvent(evt logpoller.ProgramEvent) error {
	ret := _m.Called(evt)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(logpoller.ProgramEvent) error); ok {
		r0 = rf(evt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventSaver_SaveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvent'
type EventSaver_SaveEvent_Call struct {
	*mock.Call
}

// SaveEvent is a helper method to define mock.On call
//   - evt logpoller.ProgramEvent
func (_e *EventSaver_Expecter) SaveEvent(evt interface{}) *EventSaver_SaveEvent_Call {
	return &EventSaver_SaveEvent_Call{Call: _e.mock.On("SaveEvent", evt)}
}

func (_c *EventSaver_SaveEvent_Call) Run(run func(evt logpoller.ProgramEvent)) *EventSaver_SaveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(logpoller.ProgramEvent))
	})
	return _c
}

func (_c *EventSaver_SaveEvent_Call) Return(_a0 error) *EventSaver_SaveEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventSaver_SaveEvent_Call) RunAndReturn(run func(logpoller.ProgramEvent) error) *EventSaver_SaveEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventSaver creates a new instance of EventSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventSaver {
	mock := &EventSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
