// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	iter "iter"

	logger "github.com/smartcontractkit/chainlink-common/pkg/logger"

	mock "github.com/stretchr/testify/mock"

	types "github.com/smartcontractkit/chainlink-solana/pkg/solana/logpoller/types"
)

// MockFilters is an autogenerated mock type for the filtersI type
type MockFilters struct {
	mock.Mock
}

type MockFilters_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilters) EXPECT() *MockFilters_Expecter {
	return &MockFilters_Expecter{mock: &_m.Mock}
}

// DecodeSubKey provides a mock function with given fields: ctx, lggr, raw, ID, subKeyPath
func (_m *MockFilters) DecodeSubKey(ctx context.Context, lggr logger.SugaredLogger, raw []byte, ID int64, subKeyPath []string) (interface{}, error) {
	ret := _m.Called(ctx, lggr, raw, ID, subKeyPath)

	if len(ret) == 0 {
		panic("no return value specified for DecodeSubKey")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, logger.SugaredLogger, []byte, int64, []string) (interface{}, error)); ok {
		return rf(ctx, lggr, raw, ID, subKeyPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, logger.SugaredLogger, []byte, int64, []string) interface{}); ok {
		r0 = rf(ctx, lggr, raw, ID, subKeyPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, logger.SugaredLogger, []byte, int64, []string) error); ok {
		r1 = rf(ctx, lggr, raw, ID, subKeyPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFilters_DecodeSubKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeSubKey'
type MockFilters_DecodeSubKey_Call struct {
	*mock.Call
}

// DecodeSubKey is a helper method to define mock.On call
//   - ctx context.Context
//   - lggr logger.SugaredLogger
//   - raw []byte
//   - ID int64
//   - subKeyPath []string
func (_e *MockFilters_Expecter) DecodeSubKey(ctx interface{}, lggr interface{}, raw interface{}, ID interface{}, subKeyPath interface{}) *MockFilters_DecodeSubKey_Call {
	return &MockFilters_DecodeSubKey_Call{Call: _e.mock.On("DecodeSubKey", ctx, lggr, raw, ID, subKeyPath)}
}

func (_c *MockFilters_DecodeSubKey_Call) Run(run func(ctx context.Context, lggr logger.SugaredLogger, raw []byte, ID int64, subKeyPath []string)) *MockFilters_DecodeSubKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(logger.SugaredLogger), args[2].([]byte), args[3].(int64), args[4].([]string))
	})
	return _c
}

func (_c *MockFilters_DecodeSubKey_Call) Return(_a0 interface{}, _a1 error) *MockFilters_DecodeSubKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFilters_DecodeSubKey_Call) RunAndReturn(run func(context.Context, logger.SugaredLogger, []byte, int64, []string) (interface{}, error)) *MockFilters_DecodeSubKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistinctAddresses provides a mock function with given fields: ctx
func (_m *MockFilters) GetDistinctAddresses(ctx context.Context) ([]types.PublicKey, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctAddresses")
	}

	var r0 []types.PublicKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]types.PublicKey, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []types.PublicKey); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.PublicKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFilters_GetDistinctAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistinctAddresses'
type MockFilters_GetDistinctAddresses_Call struct {
	*mock.Call
}

// GetDistinctAddresses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFilters_Expecter) GetDistinctAddresses(ctx interface{}) *MockFilters_GetDistinctAddresses_Call {
	return &MockFilters_GetDistinctAddresses_Call{Call: _e.mock.On("GetDistinctAddresses", ctx)}
}

func (_c *MockFilters_GetDistinctAddresses_Call) Run(run func(ctx context.Context)) *MockFilters_GetDistinctAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFilters_GetDistinctAddresses_Call) Return(_a0 []types.PublicKey, _a1 error) *MockFilters_GetDistinctAddresses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFilters_GetDistinctAddresses_Call) RunAndReturn(run func(context.Context) ([]types.PublicKey, error)) *MockFilters_GetDistinctAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilters provides a mock function with given fields: ctx
func (_m *MockFilters) GetFilters(ctx context.Context) (map[string]types.Filter, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFilters")
	}

	var r0 map[string]types.Filter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]types.Filter, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]types.Filter); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]types.Filter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFilters_GetFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilters'
type MockFilters_GetFilters_Call struct {
	*mock.Call
}

// GetFilters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFilters_Expecter) GetFilters(ctx interface{}) *MockFilters_GetFilters_Call {
	return &MockFilters_GetFilters_Call{Call: _e.mock.On("GetFilters", ctx)}
}

func (_c *MockFilters_GetFilters_Call) Run(run func(ctx context.Context)) *MockFilters_GetFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFilters_GetFilters_Call) Return(_a0 map[string]types.Filter, _a1 error) *MockFilters_GetFilters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFilters_GetFilters_Call) RunAndReturn(run func(context.Context) (map[string]types.Filter, error)) *MockFilters_GetFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetFiltersToBackfill provides a mock function with no fields
func (_m *MockFilters) GetFiltersToBackfill() []types.Filter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFiltersToBackfill")
	}

	var r0 []types.Filter
	if rf, ok := ret.Get(0).(func() []types.Filter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Filter)
		}
	}

	return r0
}

// MockFilters_GetFiltersToBackfill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFiltersToBackfill'
type MockFilters_GetFiltersToBackfill_Call struct {
	*mock.Call
}

// GetFiltersToBackfill is a helper method to define mock.On call
func (_e *MockFilters_Expecter) GetFiltersToBackfill() *MockFilters_GetFiltersToBackfill_Call {
	return &MockFilters_GetFiltersToBackfill_Call{Call: _e.mock.On("GetFiltersToBackfill")}
}

func (_c *MockFilters_GetFiltersToBackfill_Call) Run(run func()) *MockFilters_GetFiltersToBackfill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilters_GetFiltersToBackfill_Call) Return(_a0 []types.Filter) *MockFilters_GetFiltersToBackfill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_GetFiltersToBackfill_Call) RunAndReturn(run func() []types.Filter) *MockFilters_GetFiltersToBackfill_Call {
	_c.Call.Return(run)
	return _c
}

// HasFilter provides a mock function with given fields: ctx, name
func (_m *MockFilters) HasFilter(ctx context.Context, name string) bool {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for HasFilter")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockFilters_HasFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFilter'
type MockFilters_HasFilter_Call struct {
	*mock.Call
}

// HasFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockFilters_Expecter) HasFilter(ctx interface{}, name interface{}) *MockFilters_HasFilter_Call {
	return &MockFilters_HasFilter_Call{Call: _e.mock.On("HasFilter", ctx, name)}
}

func (_c *MockFilters_HasFilter_Call) Run(run func(ctx context.Context, name string)) *MockFilters_HasFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFilters_HasFilter_Call) Return(_a0 bool) *MockFilters_HasFilter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_HasFilter_Call) RunAndReturn(run func(context.Context, string) bool) *MockFilters_HasFilter_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementSeqNum provides a mock function with given fields: filterID
func (_m *MockFilters) IncrementSeqNum(filterID int64) int64 {
	ret := _m.Called(filterID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementSeqNum")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(filterID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockFilters_IncrementSeqNum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementSeqNum'
type MockFilters_IncrementSeqNum_Call struct {
	*mock.Call
}

// IncrementSeqNum is a helper method to define mock.On call
//   - filterID int64
func (_e *MockFilters_Expecter) IncrementSeqNum(filterID interface{}) *MockFilters_IncrementSeqNum_Call {
	return &MockFilters_IncrementSeqNum_Call{Call: _e.mock.On("IncrementSeqNum", filterID)}
}

func (_c *MockFilters_IncrementSeqNum_Call) Run(run func(filterID int64)) *MockFilters_IncrementSeqNum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockFilters_IncrementSeqNum_Call) Return(_a0 int64) *MockFilters_IncrementSeqNum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_IncrementSeqNum_Call) RunAndReturn(run func(int64) int64) *MockFilters_IncrementSeqNum_Call {
	_c.Call.Return(run)
	return _c
}

// LoadFilters provides a mock function with given fields: ctx
func (_m *MockFilters) LoadFilters(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadFilters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilters_LoadFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadFilters'
type MockFilters_LoadFilters_Call struct {
	*mock.Call
}

// LoadFilters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFilters_Expecter) LoadFilters(ctx interface{}) *MockFilters_LoadFilters_Call {
	return &MockFilters_LoadFilters_Call{Call: _e.mock.On("LoadFilters", ctx)}
}

func (_c *MockFilters_LoadFilters_Call) Run(run func(ctx context.Context)) *MockFilters_LoadFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFilters_LoadFilters_Call) Return(_a0 error) *MockFilters_LoadFilters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_LoadFilters_Call) RunAndReturn(run func(context.Context) error) *MockFilters_LoadFilters_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFilterBackfilled provides a mock function with given fields: ctx, filterID
func (_m *MockFilters) MarkFilterBackfilled(ctx context.Context, filterID int64) error {
	ret := _m.Called(ctx, filterID)

	if len(ret) == 0 {
		panic("no return value specified for MarkFilterBackfilled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, filterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilters_MarkFilterBackfilled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFilterBackfilled'
type MockFilters_MarkFilterBackfilled_Call struct {
	*mock.Call
}

// MarkFilterBackfilled is a helper method to define mock.On call
//   - ctx context.Context
//   - filterID int64
func (_e *MockFilters_Expecter) MarkFilterBackfilled(ctx interface{}, filterID interface{}) *MockFilters_MarkFilterBackfilled_Call {
	return &MockFilters_MarkFilterBackfilled_Call{Call: _e.mock.On("MarkFilterBackfilled", ctx, filterID)}
}

func (_c *MockFilters_MarkFilterBackfilled_Call) Run(run func(ctx context.Context, filterID int64)) *MockFilters_MarkFilterBackfilled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockFilters_MarkFilterBackfilled_Call) Return(_a0 error) *MockFilters_MarkFilterBackfilled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_MarkFilterBackfilled_Call) RunAndReturn(run func(context.Context, int64) error) *MockFilters_MarkFilterBackfilled_Call {
	_c.Call.Return(run)
	return _c
}

// MatchingFiltersForEncodedEvent provides a mock function with given fields: event
func (_m *MockFilters) MatchingFiltersForEncodedEvent(event types.ProgramEvent) iter.Seq[types.Filter] {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for MatchingFiltersForEncodedEvent")
	}

	var r0 iter.Seq[types.Filter]
	if rf, ok := ret.Get(0).(func(types.ProgramEvent) iter.Seq[types.Filter]); ok {
		r0 = rf(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[types.Filter])
		}
	}

	return r0
}

// MockFilters_MatchingFiltersForEncodedEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchingFiltersForEncodedEvent'
type MockFilters_MatchingFiltersForEncodedEvent_Call struct {
	*mock.Call
}

// MatchingFiltersForEncodedEvent is a helper method to define mock.On call
//   - event types.ProgramEvent
func (_e *MockFilters_Expecter) MatchingFiltersForEncodedEvent(event interface{}) *MockFilters_MatchingFiltersForEncodedEvent_Call {
	return &MockFilters_MatchingFiltersForEncodedEvent_Call{Call: _e.mock.On("MatchingFiltersForEncodedEvent", event)}
}

func (_c *MockFilters_MatchingFiltersForEncodedEvent_Call) Run(run func(event types.ProgramEvent)) *MockFilters_MatchingFiltersForEncodedEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ProgramEvent))
	})
	return _c
}

func (_c *MockFilters_MatchingFiltersForEncodedEvent_Call) Return(_a0 iter.Seq[types.Filter]) *MockFilters_MatchingFiltersForEncodedEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_MatchingFiltersForEncodedEvent_Call) RunAndReturn(run func(types.ProgramEvent) iter.Seq[types.Filter]) *MockFilters_MatchingFiltersForEncodedEvent_Call {
	_c.Call.Return(run)
	return _c
}

// PruneFilters provides a mock function with given fields: ctx
func (_m *MockFilters) PruneFilters(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PruneFilters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilters_PruneFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneFilters'
type MockFilters_PruneFilters_Call struct {
	*mock.Call
}

// PruneFilters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFilters_Expecter) PruneFilters(ctx interface{}) *MockFilters_PruneFilters_Call {
	return &MockFilters_PruneFilters_Call{Call: _e.mock.On("PruneFilters", ctx)}
}

func (_c *MockFilters_PruneFilters_Call) Run(run func(ctx context.Context)) *MockFilters_PruneFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFilters_PruneFilters_Call) Return(_a0 error) *MockFilters_PruneFilters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_PruneFilters_Call) RunAndReturn(run func(context.Context) error) *MockFilters_PruneFilters_Call {
	_c.Call.Return(run)
	return _c
}

// PruneLogs provides a mock function with given fields: ctx
func (_m *MockFilters) PruneLogs(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PruneLogs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilters_PruneLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneLogs'
type MockFilters_PruneLogs_Call struct {
	*mock.Call
}

// PruneLogs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFilters_Expecter) PruneLogs(ctx interface{}) *MockFilters_PruneLogs_Call {
	return &MockFilters_PruneLogs_Call{Call: _e.mock.On("PruneLogs", ctx)}
}

func (_c *MockFilters_PruneLogs_Call) Run(run func(ctx context.Context)) *MockFilters_PruneLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFilters_PruneLogs_Call) Return(_a0 error) *MockFilters_PruneLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_PruneLogs_Call) RunAndReturn(run func(context.Context) error) *MockFilters_PruneLogs_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFilter provides a mock function with given fields: ctx, filter
func (_m *MockFilters) RegisterFilter(ctx context.Context, filter types.Filter) error {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for RegisterFilter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Filter) error); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilters_RegisterFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFilter'
type MockFilters_RegisterFilter_Call struct {
	*mock.Call
}

// RegisterFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter types.Filter
func (_e *MockFilters_Expecter) RegisterFilter(ctx interface{}, filter interface{}) *MockFilters_RegisterFilter_Call {
	return &MockFilters_RegisterFilter_Call{Call: _e.mock.On("RegisterFilter", ctx, filter)}
}

func (_c *MockFilters_RegisterFilter_Call) Run(run func(ctx context.Context, filter types.Filter)) *MockFilters_RegisterFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.Filter))
	})
	return _c
}

func (_c *MockFilters_RegisterFilter_Call) Return(_a0 error) *MockFilters_RegisterFilter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_RegisterFilter_Call) RunAndReturn(run func(context.Context, types.Filter) error) *MockFilters_RegisterFilter_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterFilter provides a mock function with given fields: ctx, name
func (_m *MockFilters) UnregisterFilter(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterFilter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilters_UnregisterFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterFilter'
type MockFilters_UnregisterFilter_Call struct {
	*mock.Call
}

// UnregisterFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockFilters_Expecter) UnregisterFilter(ctx interface{}, name interface{}) *MockFilters_UnregisterFilter_Call {
	return &MockFilters_UnregisterFilter_Call{Call: _e.mock.On("UnregisterFilter", ctx, name)}
}

func (_c *MockFilters_UnregisterFilter_Call) Run(run func(ctx context.Context, name string)) *MockFilters_UnregisterFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFilters_UnregisterFilter_Call) Return(_a0 error) *MockFilters_UnregisterFilter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilters_UnregisterFilter_Call) RunAndReturn(run func(context.Context, string) error) *MockFilters_UnregisterFilter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStartingBlocks provides a mock function with given fields: startingBlocks
func (_m *MockFilters) UpdateStartingBlocks(startingBlocks int64) {
	_m.Called(startingBlocks)
}

// MockFilters_UpdateStartingBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStartingBlocks'
type MockFilters_UpdateStartingBlocks_Call struct {
	*mock.Call
}

// UpdateStartingBlocks is a helper method to define mock.On call
//   - startingBlocks int64
func (_e *MockFilters_Expecter) UpdateStartingBlocks(startingBlocks interface{}) *MockFilters_UpdateStartingBlocks_Call {
	return &MockFilters_UpdateStartingBlocks_Call{Call: _e.mock.On("UpdateStartingBlocks", startingBlocks)}
}

func (_c *MockFilters_UpdateStartingBlocks_Call) Run(run func(startingBlocks int64)) *MockFilters_UpdateStartingBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockFilters_UpdateStartingBlocks_Call) Return() *MockFilters_UpdateStartingBlocks_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFilters_UpdateStartingBlocks_Call) RunAndReturn(run func(int64)) *MockFilters_UpdateStartingBlocks_Call {
	_c.Run(run)
	return _c
}

// NewMockFilters creates a new instance of MockFilters. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilters(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilters {
	mock := &MockFilters{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
