// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	logpoller "github.com/smartcontractkit/chainlink-solana/pkg/solana/logpoller"
	mock "github.com/stretchr/testify/mock"
)

// ProgramEventProcessor is an autogenerated mock type for the ProgramEventProcessor type
type ProgramEventProcessor struct {
	mock.Mock
}

type ProgramEventProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *ProgramEventProcessor) EXPECT() *ProgramEventProcessor_Expecter {
	return &ProgramEventProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: _a0
func (_m *ProgramEventProcessor) Process(_a0 logpoller.ProgramEvent) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(logpoller.ProgramEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProgramEventProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type ProgramEventProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - _a0 logpoller.ProgramEvent
func (_e *ProgramEventProcessor_Expecter) Process(_a0 interface{}) *ProgramEventProcessor_Process_Call {
	return &ProgramEventProcessor_Process_Call{Call: _e.mock.On("Process", _a0)}
}

func (_c *ProgramEventProcessor_Process_Call) Run(run func(_a0 logpoller.ProgramEvent)) *ProgramEventProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(logpoller.ProgramEvent))
	})
	return _c
}

func (_c *ProgramEventProcessor_Process_Call) Return(_a0 error) *ProgramEventProcessor_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProgramEventProcessor_Process_Call) RunAndReturn(run func(logpoller.ProgramEvent) error) *ProgramEventProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewProgramEventProcessor creates a new instance of ProgramEventProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProgramEventProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProgramEventProcessor {
	mock := &ProgramEventProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
