// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	metrics "github.com/smartcontractkit/chainlink-solana/pkg/monitoring/metrics"
	mock "github.com/stretchr/testify/mock"

	prometheus "github.com/prometheus/client_golang/prometheus"
)

// FeedBalances is an autogenerated mock type for the FeedBalances type
type FeedBalances struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: input
func (_m *FeedBalances) Cleanup(input metrics.FeedBalanceInput) {
	_m.Called(input)
}

// Exists provides a mock function with given fields: balanceAccountName
func (_m *FeedBalances) Exists(balanceAccountName string) (*prometheus.GaugeVec, bool) {
	ret := _m.Called(balanceAccountName)

	var r0 *prometheus.GaugeVec
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*prometheus.GaugeVec, bool)); ok {
		return rf(balanceAccountName)
	}
	if rf, ok := ret.Get(0).(func(string) *prometheus.GaugeVec); ok {
		r0 = rf(balanceAccountName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prometheus.GaugeVec)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(balanceAccountName)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// SetBalance provides a mock function with given fields: balance, input
func (_m *FeedBalances) SetBalance(balance uint64, input metrics.FeedBalanceInput) {
	_m.Called(balance, input)
}

type mockConstructorTestingTNewFeedBalances interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeedBalances creates a new instance of FeedBalances. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeedBalances(t mockConstructorTestingTNewFeedBalances) *FeedBalances {
	mock := &FeedBalances{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
