// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NodeBalances is an autogenerated mock type for the NodeBalances type
type NodeBalances struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: address, operator
func (_m *NodeBalances) Cleanup(address string, operator string) {
	_m.Called(address, operator)
}

// SetBalance provides a mock function with given fields: balance, address, operator
func (_m *NodeBalances) SetBalance(balance uint64, address string, operator string) {
	_m.Called(balance, address, operator)
}

// NewNodeBalances creates a new instance of NodeBalances. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeBalances(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeBalances {
	mock := &NodeBalances{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
