// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	metrics "github.com/smartcontractkit/chainlink-solana/pkg/monitoring/metrics"
	mock "github.com/stretchr/testify/mock"
)

// NodeSuccess is an autogenerated mock type for the NodeSuccess type
type NodeSuccess struct {
	mock.Mock
}

// Add provides a mock function with given fields: count, i
func (_m *NodeSuccess) Add(count int, i metrics.NodeFeedInput) {
	_m.Called(count, i)
}

// Cleanup provides a mock function with given fields: i
func (_m *NodeSuccess) Cleanup(i metrics.NodeFeedInput) {
	_m.Called(i)
}

type mockConstructorTestingTNewNodeSuccess interface {
	mock.TestingT
	Cleanup(func())
}

// NewNodeSuccess creates a new instance of NodeSuccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNodeSuccess(t mockConstructorTestingTNewNodeSuccess) *NodeSuccess {
	mock := &NodeSuccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
