// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	metrics "github.com/smartcontractkit/chainlink-solana/pkg/monitoring/metrics"
	mock "github.com/stretchr/testify/mock"
)

// ReportObservations is an autogenerated mock type for the ReportObservations type
type ReportObservations struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: feedInput
func (_m *ReportObservations) Cleanup(feedInput metrics.FeedInput) {
	_m.Called(feedInput)
}

// SetCount provides a mock function with given fields: count, feedInput
func (_m *ReportObservations) SetCount(count uint8, feedInput metrics.FeedInput) {
	_m.Called(count, feedInput)
}

type mockConstructorTestingTNewReportObservations interface {
	mock.TestingT
	Cleanup(func())
}

// NewReportObservations creates a new instance of ReportObservations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReportObservations(t mockConstructorTestingTNewReportObservations) *ReportObservations {
	mock := &ReportObservations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
