// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	types "github.com/smartcontractkit/chainlink-solana/pkg/monitoring/types"
	mock "github.com/stretchr/testify/mock"
)

// SlotHeight is an autogenerated mock type for the SlotHeight type
type SlotHeight struct {
	mock.Mock
}

type SlotHeight_Expecter struct {
	mock *mock.Mock
}

func (_m *SlotHeight) EXPECT() *SlotHeight_Expecter {
	return &SlotHeight_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields:
func (_m *SlotHeight) Cleanup() {
	_m.Called()
}

// SlotHeight_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type SlotHeight_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *SlotHeight_Expecter) Cleanup() *SlotHeight_Cleanup_Call {
	return &SlotHeight_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *SlotHeight_Cleanup_Call) Run(run func()) *SlotHeight_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SlotHeight_Cleanup_Call) Return() *SlotHeight_Cleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *SlotHeight_Cleanup_Call) RunAndReturn(run func()) *SlotHeight_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: slot, chain, url
func (_m *SlotHeight) Set(slot types.SlotHeight, chain string, url string) {
	_m.Called(slot, chain, url)
}

// SlotHeight_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type SlotHeight_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - slot types.SlotHeight
//   - chain string
//   - url string
func (_e *SlotHeight_Expecter) Set(slot interface{}, chain interface{}, url interface{}) *SlotHeight_Set_Call {
	return &SlotHeight_Set_Call{Call: _e.mock.On("Set", slot, chain, url)}
}

func (_c *SlotHeight_Set_Call) Run(run func(slot types.SlotHeight, chain string, url string)) *SlotHeight_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.SlotHeight), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SlotHeight_Set_Call) Return() *SlotHeight_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *SlotHeight_Set_Call) RunAndReturn(run func(types.SlotHeight, string, string)) *SlotHeight_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewSlotHeight creates a new instance of SlotHeight. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSlotHeight(t interface {
	mock.TestingT
	Cleanup(func())
}) *SlotHeight {
	mock := &SlotHeight{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
