[toolchain]
anchor_version = "0.31.0"

[features]
resolution = false
skip-lint = false

[programs.localnet]
hello_world = "2zqDPfT7nqvL7NrptW13BVmaXcZqyin7RubAGfxEK1om"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "../../id.json"

[scripts]
test = "pnpm run test"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "9kRNTZmoZSiTBuXC62dzK9E7gC7huYgcmRRhYv3i4osC"
program = "../../target/deploy/store.so"
