// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SimpleKeystore is an autogenerated mock type for the SimpleKeystore type
type SimpleKeystore struct {
	mock.Mock
}

// Sign provides a mock function with given fields: ctx, account, data
func (_m *SimpleKeystore) Sign(ctx context.Context, account string, data []byte) ([]byte, error) {
	ret := _m.Called(ctx, account, data)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) ([]byte, error)); ok {
		return rf(ctx, account, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) []byte); ok {
		r0 = rf(ctx, account, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, account, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSimpleKeystore interface {
	mock.TestingT
	Cleanup(func())
}

// NewSimpleKeystore creates a new instance of SimpleKeystore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSimpleKeystore(t mockConstructorTestingTNewSimpleKeystore) *SimpleKeystore {
	mock := &SimpleKeystore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
