name: DependencyUpdater
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # check every day at midnight UTC
  
jobs:
  E2E-Solana-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout branch that it is called from
      - name: check for solana image updates
        id: solImage
        run: |
          make upgrade-e2e-solana-image
          image=$(curl https://api.github.com/repos/solana-labs/solana/releases/latest | jq -r '.name')
          echo "image=$image" >> "$GITHUB_OUTPUT"
      - name: Create pull request
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50 # v6.0.0
        with:
          title: "[automated] bump solana dependencies"
          branch: bump/dependencies
          branch-suffix: timestamp
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          reviewers: aalu1418
          commit-message: "[automated] bump solana dependencies"
          body: "Latest Solana mainnet release is [\"${{ steps.solImage.outputs.image }}\"](https://github.com/solana-labs/solana/releases/latest)"

