name: DependencyUpdater
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # check every day at midnight UTC
  
jobs:
  E2E-Solana-Image:
    uses: ./.github/workflows/open-pr.yml
    with:
      run: |
        make upgrade-solana-image
        image=$(curl https://api.github.com/repos/anza-xyz/agave/releases/latest | jq -r '.tag_name')

        # outputs
        echo "name=bump/solana-$image" >> "$GITHUB_OUTPUT"
        echo "prTitle=[automated] bump solana image to $image" >> "$GITHUB_OUTPUT"
        echo "prBody=Latest Solana mainnet release is [$image](https://github.com/anza-xyz/agave/releases/latest)" >> "$GITHUB_OUTPUT"
        echo "commitString=[automated] bump solana dependencies" >> "$GITHUB_OUTPUT"
    secrets: inherit
