name: Gauntlet

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Parse Node version
        id: node-version
        run: |
          NODE_VERSION=$(cat ./.tool-versions | grep nodejs | sed -En "s/nodejs.(.*)/\1/p")
          echo "::set-output name=NODE_VERSION::${NODE_VERSION}"
      - name: Setup Node ${{ steps.node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
      - name: Install
        run: |
          npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          yarn --cwd ./gauntlet install --frozen-lockfile
      - name: Build
        run: |
          yarn --cwd ./gauntlet build
      - name: Run Gauntlet
        run: |
          yarn --cwd ./gauntlet gauntlet

  format:
    runs-on: ubuntu-latest
    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Parse Node version
        id: node-version
        run: |
          NODE_VERSION=$(cat ./.tool-versions | grep nodejs | sed -En "s/nodejs.(.*)/\1/p")
          echo "::set-output name=NODE_VERSION::${NODE_VERSION}"
      - name: Setup Node ${{ steps.node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
      - name: Install
        run: |
          npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          yarn --cwd ./gauntlet install --frozen-lockfile
      - name: Lint
        run: |
          yarn --cwd ./gauntlet lint:format

  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Parse Node version
        id: node-version
        run: |
          NODE_VERSION=$(cat ./.tool-versions | grep nodejs | sed -En "s/nodejs.(.*)/\1/p")
          echo "::set-output name=NODE_VERSION::${NODE_VERSION}"
      - name: Setup Node ${{ steps.node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
      - name: Install
        run: |
          npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          yarn --cwd ./gauntlet install --frozen-lockfile
      - name: test:ci
        run: |
          yarn --cwd ./gauntlet test:ci
