name: gauntlet

on:
  pull_request:

jobs:
  tool_versions:
    name: Get the tool versions
    runs-on: ubuntu-latest
    outputs:
      nodejs_version: ${{ steps.tool-versions.outputs.nodejs_version }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: smartcontractkit/tool-versions-to-env-action@v1.0.8
        id: tool-versions

  gauntlet_build:
    name: Gauntlet Build
    runs-on: ubuntu-latest
    needs: [tool_versions]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Setup Node ${{ needs.tool_versions.outputs.nodejs_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.tool_versions.outputs.nodejs_version }}
      - name: Install
        run: yarn --cwd ./gauntlet install --frozen-lockfile
      - name: Build
        run: yarn --cwd ./gauntlet build
      - name: Run Gauntlet
        run: yarn --cwd ./gauntlet gauntlet

  gauntlet_format:
    name: Gauntlet Format
    runs-on: ubuntu-latest
    needs: [tool_versions]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Setup Node ${{ needs.tool_versions.outputs.nodejs_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.tool_versions.outputs.nodejs_version }}
      - name: Install
        run: yarn --cwd ./gauntlet install --frozen-lockfile
      - name: Lint
        run: yarn --cwd ./gauntlet lint:format

  gauntlet_run_tests:
    name: Gauntlet Run Tests
    runs-on: ubuntu-latest
    needs: [tool_versions]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Setup Node ${{ needs.tool_versions.outputs.nodejs_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.tool_versions.outputs.nodejs_version }}
      - name: Install
        run: yarn --cwd ./gauntlet install --frozen-lockfile
      - name: test:ci
        run: yarn --cwd ./gauntlet test:ci
