name: gauntlet

on:
  push:

jobs:
  gauntlet_build:
    name: Gauntlet Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: .tool-versions to .env
        run: ./scripts/tool-versions-to-env.sh
      - name: dotenv
        uses: actions/dotenv-action@v0.2.7
        id: dotenv
      - name: Setup Node ${{ steps.node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
      - name: Install
        run: |
          npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          yarn --cwd ./gauntlet install --frozen-lockfile
      - name: Build
        run: |
          yarn --cwd ./gauntlet build
      - name: Run Gauntlet
        run: |
          yarn --cwd ./gauntlet gauntlet

  gauntlet_format:
    name: Gauntlet Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: .tool-versions to .env
        run: ./scripts/tool-versions-to-env.sh
      - name: dotenv
        uses: actions/dotenv-action@v0.2.7
        id: dotenv
      - name: Setup Node ${{ steps.dotenv.outputs.NODEJS_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.dotenv.outputs.NODEJS_VERSION }}
      - name: Install
        run: yarn --cwd ./gauntlet install --frozen-lockfile
      - name: Lint
        run: yarn --cwd ./gauntlet lint:format

  gauntlet_run_tests:
    name: Gauntlet Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: .tool-versions to .env
        run: ./scripts/tool-versions-to-env.sh
      - name: dotenv
        uses: actions/dotenv-action@v0.2.7
        id: dotenv
      - name: Setup Node ${{ steps.dotenv.outputs.NODEJS_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.dotenv.outputs.NODEJS_VERSION }}
      - name: Install
        run: yarn --cwd ./gauntlet install --frozen-lockfile
      - name: test:ci
        run: yarn --cwd ./gauntlet test:ci
