name: golangci_lint

on:
  pull_request:

jobs:
  golang_lint:
    name: Golang Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: smartcontractkit/tool-versions-to-env-action@v1.0.8
        id: tool-versions
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ steps.tool-versions.outputs.golangci-lint_version }}
          args: --enable=gofmt --tests=false --exclude-use-default --timeout=5m0s
          only-new-issues: true
      - name: Store lint report artifact
        if: always()
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: golangci-lint-report
          path: ./golangci-lint-report.xml