name: golangci_lint

on:
  pull_request:

jobs:
  golang_lint_integration_tests:
    name: Golang Lint Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Install Nix
        uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: golangci-lint
        run: nix develop -c make lint-go-integration-tests
      - name: Store lint report artifact
        if: always()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: golangci-lint-integration-tests-report
          path: ./integration-tests/golangci-lint-integration-tests-report.xml

  golang_lint_relay:
    name: Golang Lint Relay tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Install Nix
        uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: golangci-lint
        run: nix develop -c make lint-go-relay
      - name: Store lint report artifact
        if: always()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: golangci-lint-relay-report
          path: ./pkg/golangci-lint-relay-report.xml