name: golangci_lint

on: [pull_request]

jobs:
  golang_lint_integration_tests:
    name: Golang Lint Integration Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Get golangci-lint version from asdf
        id: get-version
        run: |
          version=$(grep '^golangci-lint ' .tool-versions | awk '{print $2}')
          echo "version=${version}" | tee -a "$GITHUB_OUTPUT"
      - name: Run golangci-lint (integration-tests)
        if: ${{ always() && !contains(join(github.event.pull_request.labels.*.name, ' '), 'allow-lint-issues') }}
        uses: smartcontractkit/.github/actions/ci-lint-go@cdcf67030997adc322ddb2ad48949f394f5b04a3 #ci-lint-go/3.0.0
        env:
          checkout-repo: false
          golangci-lint-version: v${{ steps.get-version.outputs.version }}
          go-directory: integration-tests
          golangci-lint-config:  ${{ github.workspace }}/.golangci.yml
  golang_lint_relay:
    name: Golang Lint Relay tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Get golangci-lint version from asdf
        id: get-version
        run: |
          version=$(grep '^golangci-lint ' .tool-versions | awk '{print $2}')
          echo "version=${version}" | tee -a "$GITHUB_OUTPUT"

      - name: Run golangci-lint (relay)
        if: ${{ always() && !contains(join(github.event.pull_request.labels.*.name, ' '), 'allow-lint-issues') }}
        uses: smartcontractkit/.github/actions/ci-lint-go@cdcf67030997adc322ddb2ad48949f394f5b04a3 #ci-lint-go/3.0.0
        with:
          checkout-repo: false
          golangci-lint-version: v${{ steps.get-version.outputs.version }}
          go-directory: pkg 
          golangci-lint-args:
            --output.checkstyle.path=${{ github.workspace }}/pkg/golangci-lint-report.xml --output.text.path=stdout
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golangci-lint-relay-report
          path: ${{ github.workspace }}/pkg/golangci-lint-report.xml
