name: Lint GH Workflows
on:
  pull_request:
jobs:
  lint_workflows:
    name: Validate Github Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v7
      - name: Run actionlint
        uses: reviewdog/action-actionlint@d290e336d5a743810aef4404f757dc862276d2ae # v1.73.4
