name: "Compile SOM"

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Docker Buildx Build
        run: docker buildx build --file ops/monitoring/Dockerfile ./
