on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  nix-packages-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # nix:v2.24.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "sandbox = false"

      - name: Build and test solana-test-validator
        run: nix run .#solana-test-validator

      - name: Build solana-cli-env
        run: nix build .#solana-cli-env --print-out-paths

      - name: Test solana-cli-shell
        run: nix develop .#solana-cli


        