on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  nix-packages-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "sandbox = false"

      - name: Build and test solana-test-validator
        run: nix run .#solana-test-validator

      - name: Build solana-cli-env
        run: nix build .#solana-cli-env --print-out-paths

      - name: Test solana-cli-shell
        run: nix develop .#solana-cli


