name: relay

on:
  push:

jobs:
  relay_run_unit_tests:
    name: Relay Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - uses: smartcontractkit/tool-versions-to-env-action@v1.0.7
        id: tool-versions
      - name: Setup go ${{ steps.tool-versions.outputs.golang_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.tool-versions.outputs.golang_version }}
      - name: Install Solana CLI
        run: ./scripts/install-solana-ci.sh
      - name: Build
        run: cd ./relayer && go build -v ./pkg/...
      - name: Test
        run: cd ./relayer && go test ./pkg/... -v
      - name: Test with the race detector enabled
        run: cd ./relayer && go test ./pkg/... -v -race -count=10
