name: relay

on:
  pull_request:

jobs:
  relay_run_unit_tests:
    name: Relay Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Install Solana CLI
        run: ./scripts/install-solana-ci.sh
      - name: Build
        run: go build -v ./pkg/...
      - name: Test
        run: go test ./pkg/... -v
      - name: Test with the race detector enabled
        run: go test ./pkg/... -v -race -count=10
