name: Relay

on:
  push:

jobs:
  Relay_Run_Unit_Tests:
    name: Relay Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: nix develop -c go build -v ./pkg/...
      - name: Test
        run: nix develop -c go test ./pkg/... -v
      - name: Test with the race detector enabled
        run: nix develop -c go test ./pkg/... -v -race -count=10
