name: rust
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.18.0
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1

    steps:
    - uses: actions/checkout@v2
    - run: echo $HOME
    - run: echo $PATH
    - run: solana-keygen new -o id.json
    - run: yarn install --frozen-lockfile
    - run: anchor test
