name: rust
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.18.0
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - run: echo $HOME
    - run: echo $PATH
    - run: |
        npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        yarn install --frozen-lockfile
    - run: solana-keygen new -o id.json
    - run: anchor test
