name: rust
on: [push]

defaults:
  run:
    working-directory: contracts

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.22.1
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1

    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-v2-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-v2-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo target dir
      uses: actions/cache@v2.1.7
      with:
        path: contracts/target
        key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - run: solana-keygen new -o id.json
    - run: yarn install --frozen-lockfile
    - run: anchor test
    - run: |
       cd examples/hello-world
       yarn install --frozen-lockfile
       anchor test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.22.1
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1

    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-v2-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-v2-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo target dir
      uses: actions/cache@v2.1.7
      with:
        path: contracts/target
        key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - run: cargo check
    - run: cargo clippy -- -D warnings
