name: rust
on:
  push:

defaults:
  run:
    working-directory: contracts

jobs:
  rust_run_anchor_tests:
    name: Rust Run Anchor Tests
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.24.2
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1

    steps:
    - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
    - name: Cache cargo registry
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-v2-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-v2-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo target dir
      uses: actions/cache@v2.1.7
      with:
        path: contracts/target
        key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - run: solana-keygen new -o id.json
    - name: Compile typescript client
      run: |
       cd ../ts
       yarn install --frozen-lockfile
       yarn build
    - run: yarn install --frozen-lockfile
    - run: anchor test
    - run: |
       cd examples/hello-world
       yarn install --frozen-lockfile
       anchor test

  rust_lint:
    name: Rust Lint
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.24.2
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1

    steps:
    - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
    - name: Cache cargo registry
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-v2-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-v2-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo target dir
      uses: actions/cache@v2.1.7
      with:
        path: contracts/target
        key: ${{ runner.os }}-v2-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - run: cargo check
    - run: cargo clippy -- -D warnings
