name: rust
on: [push]

defaults:
  run:
    working-directory: contracts

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.18.0
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1

    steps:
    - uses: actions/checkout@v2
    - run: solana-keygen new -o id.json
    - run: yarn install --frozen-lockfile
    - run: anchor test
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: projectserum/build:v0.18.0
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1

    steps:
    - uses: actions/checkout@v2
    - run: cargo check
    - run: cargo clippy -- -D warnings
