name: E2E Soak Test
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
    inputs:
      cl_branch_ref:
        description: Chainlink repo branch to integrate with
        required: true
        default: develop
        type: string
jobs:
  get_projectserum_version:
    name: Get ProjectSerum Version
    environment: integration
    runs-on: ubuntu-latest
    outputs:
      projectserum_version: ${{ steps.psversion.outputs.projectserum_version }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Get ProjectSerum Version
        id: psversion
        uses: ./.github/actions/projectserum_version
  soak_testing_build_contracts:
    name: Soak Testing Build Contracts
    environment: integration
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: [get_projectserum_version]
    container:
      image: projectserum/build:${{ needs.get_projectserum_version.outputs.projectserum_version }}
      env:
        RUSTUP_HOME: "/root/.rustup"
        FORCE_COLOR: 1
    steps:
      - name: Checkout the repo
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Build contracts
        uses: ./.github/actions/build_contract_artifacts
  soak_testing_build_custom_chainlink_image:
    name: Soak Testing Build Custom Chainlink Image
    runs-on: ubuntu-latest
    environment: integration
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Build Image
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/build-image@v2.0.21
        with:
          cl_repo: smartcontractkit/chainlink
          # by default we are integrating with develop
          cl_ref: ${{ github.event.inputs.cl_branch_ref }}
          # commit of the caller branch
          dep_solana_sha: ${{ github.sha }}
          push_tag: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink:custom.${{ github.sha }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
  soak_testing_run_test:
    name: Soak Testing Run Test
    environment: integration
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: [soak_testing_build_contracts, soak_testing_build_custom_chainlink_image]
    env:
      CGO_ENABLED: 1
      CHAINLINK_COMMIT_SHA: ${{ github.sha }}
      CHAINLINK_ENV_USER: ${{ github.actor }}
      TEST_TRIGGERED_BY: solana-soak
      TEST_LOG_LEVEL: debug
    steps:
      - name: Checkout the repo
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Run Tests
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@v2.0.21
        with:
          test_command_to_run: make test_ocr_soak
          go_mod_path: ./tests/go.mod
          cl_repo: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
          cl_image_tag: custom.${{ github.sha }}
          download_contract_artifacts_path: contracts/target/deploy
          artifacts_location: /home/runner/work/chainlink-solana/chainlink-solana/tests/e2e/soak/logs
          publish_report_paths: ./tests-soak-report.xml
          publish_check_name: Chaos Test Results
          token: ${{ secrets.GITHUB_TOKEN }}
          triggered_by: ${{ env.TEST_TRIGGERED_BY }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
