// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	logpoller "github.com/smartcontractkit/chainlink-solana/pkg/solana/logpoller"
	mock "github.com/stretchr/testify/mock"

	query "github.com/smartcontractkit/chainlink-common/pkg/types/query"
)

// EventsReader is an autogenerated mock type for the EventsReader type
type EventsReader struct {
	mock.Mock
}

type EventsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *EventsReader) EXPECT() *EventsReader_Expecter {
	return &EventsReader_Expecter{mock: &_m.Mock}
}

// FilteredLogs provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *EventsReader) FilteredLogs(_a0 context.Context, _a1 []query.Expression, _a2 query.LimitAndSort, _a3 string) ([]logpoller.Log, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for FilteredLogs")
	}

	var r0 []logpoller.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []query.Expression, query.LimitAndSort, string) ([]logpoller.Log, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []query.Expression, query.LimitAndSort, string) []logpoller.Log); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]logpoller.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []query.Expression, query.LimitAndSort, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsReader_FilteredLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilteredLogs'
type EventsReader_FilteredLogs_Call struct {
	*mock.Call
}

// FilteredLogs is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []query.Expression
//   - _a2 query.LimitAndSort
//   - _a3 string
func (_e *EventsReader_Expecter) FilteredLogs(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *EventsReader_FilteredLogs_Call {
	return &EventsReader_FilteredLogs_Call{Call: _e.mock.On("FilteredLogs", _a0, _a1, _a2, _a3)}
}

func (_c *EventsReader_FilteredLogs_Call) Run(run func(_a0 context.Context, _a1 []query.Expression, _a2 query.LimitAndSort, _a3 string)) *EventsReader_FilteredLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]query.Expression), args[2].(query.LimitAndSort), args[3].(string))
	})
	return _c
}

func (_c *EventsReader_FilteredLogs_Call) Return(_a0 []logpoller.Log, _a1 error) *EventsReader_FilteredLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventsReader_FilteredLogs_Call) RunAndReturn(run func(context.Context, []query.Expression, query.LimitAndSort, string) ([]logpoller.Log, error)) *EventsReader_FilteredLogs_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with given fields:
func (_m *EventsReader) Ready() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventsReader_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type EventsReader_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *EventsReader_Expecter) Ready() *EventsReader_Ready_Call {
	return &EventsReader_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *EventsReader_Ready_Call) Run(run func()) *EventsReader_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventsReader_Ready_Call) Return(_a0 error) *EventsReader_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventsReader_Ready_Call) RunAndReturn(run func() error) *EventsReader_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFilter provides a mock function with given fields: _a0, _a1
func (_m *EventsReader) RegisterFilter(_a0 context.Context, _a1 logpoller.Filter) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RegisterFilter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, logpoller.Filter) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventsReader_RegisterFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFilter'
type EventsReader_RegisterFilter_Call struct {
	*mock.Call
}

// RegisterFilter is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 logpoller.Filter
func (_e *EventsReader_Expecter) RegisterFilter(_a0 interface{}, _a1 interface{}) *EventsReader_RegisterFilter_Call {
	return &EventsReader_RegisterFilter_Call{Call: _e.mock.On("RegisterFilter", _a0, _a1)}
}

func (_c *EventsReader_RegisterFilter_Call) Run(run func(_a0 context.Context, _a1 logpoller.Filter)) *EventsReader_RegisterFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(logpoller.Filter))
	})
	return _c
}

func (_c *EventsReader_RegisterFilter_Call) Return(_a0 error) *EventsReader_RegisterFilter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventsReader_RegisterFilter_Call) RunAndReturn(run func(context.Context, logpoller.Filter) error) *EventsReader_RegisterFilter_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *EventsReader) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventsReader_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type EventsReader_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EventsReader_Expecter) Start(ctx interface{}) *EventsReader_Start_Call {
	return &EventsReader_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *EventsReader_Start_Call) Run(run func(ctx context.Context)) *EventsReader_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EventsReader_Start_Call) Return(_a0 error) *EventsReader_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventsReader_Start_Call) RunAndReturn(run func(context.Context) error) *EventsReader_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventsReader creates a new instance of EventsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventsReader {
	mock := &EventsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
